In [1]:
import pandas as pd

In [2]:
df_dataset = pd.read_excel('./data/dataset.xlsx')
df_dataset2 = pd.read_excel('./data/dataset.No2.xlsx')

In [3]:
df_dataset.rank

<bound method NDFrame.rank of                        movieNm   movieCd      openDt  rank  scrnCnt  \
0                       황금 나침반  20070551  2007-12-18     1      293
21               내셔널 트레져:비밀의 책  20070549  2007-12-19     2      246
37                     기다리다 미쳐  20070661  2008-01-01     3      238
53                    색즉시공 시즌2  20070637  2007-12-12     4      208
62                P.S. 아이 러브 유  20071003  2008-01-03     6      184
71                     어거스트 러쉬  20070585  2007-11-29     9      124
80                       꿀벌대소동  20070563  2008-01-03     1      208
110               우리 생애 최고의 순간  20070382  2008-01-10     1      379
152                      무방비도시  20071064  2008-01-10     2      296
179                        미스트  20071042  2008-01-10     3      188
197                  마법에 걸린 사랑  20070566  2008-01-10     5      239
217    스위니 토드 : 어느 잔혹한 이발사 이야기  20080009  2008-01-17     2      224
233                  뜨거운 것이 좋아  20070660  2008-01-17     4      229
247                      클로버필드  20070672  2008-01-24     2      259
261                       더 게임  20071675  2008-01-30     1      266
282                 슈퍼맨이었던 사나이  20071067  2008-01-31     3      349
296                         명장  20080013  2008-01-30     5      227
310                    6년째 연애중  20070548  2008-02-05     1      289
333                     마지막 선물  20080014  2008-02-05     7      250
342                         점퍼  20080047  2008-02-14    10        6
371                        추격자  20080046  2008-02-14     2      391
454                스파이더위크가의 비밀  20080038  2008-02-14     5      158
477             데스노트 L: 새로운 시작  20080062  2008-02-21     3      233
491                         바보  20072151  2008-02-28     2      238
519                 27번의 결혼리허설  20080141  2008-03-06     4      216
533                   마이 뉴 파트너  20080142  2008-03-06     5      218
547             스텝업 2 : 더 스트리트  20080149  2008-03-13     7       12
576                  10,000 BC  20080148  2008-03-13     1      347
598                    천일의 스캔들  20080230  2008-03-20     5      117
627                  삼국지:용의 부활  20080291  2008-04-03     8       10
...                        ...       ...         ...   ...      ...
22495                  아토믹 블론드  20179491  2017-08-30     6      471
22502                 살인자의 기억법  20154909  2017-09-06     1      884
22529                       그것  20179696  2017-09-06     2      752
22549                 아이 캔 스피크  20174142  2017-09-21     7       28
22591                 베이비 드라이버  20171090  2017-09-14     2      669
22611                 아메리칸 메이드  20177541  2017-09-14     3      653
22624                     범죄도시  20172742  2017-10-03     9       13
22685                     남한산성  20165450  2017-10-03     7       12
22721               킹스맨: 골든 서클  20175222  2017-09-27     1     1687
22749             블레이드 러너 2049  20168282  2017-10-12     8      153
22765                    희생부활자  20154907  2017-10-12     5        9
22773                      부라더  20172603  2017-11-02     8        8
22799                   대장 김창수  20164424  2017-10-19     9       12
22816                     지오스톰  20173694  2017-10-19     2      669
22833                토르: 라그나로크  20175121  2017-10-25     1     1601
22876                       침묵  20169643  2017-11-02     3      612
22889                       미옥  20161681  2017-11-09     7        5
22897                  해피 데스데이  20174622  2017-11-08     3      472
22926                       채비  20175441  2017-11-09     6      452
22945                        꾼  20165748  2017-11-22     9       13
22979                  저스티스 리그  20168221  2017-11-15     1     1192
23001                      7호실  20168754  2017-11-15     3      629
23015                    기억의 밤  20173581  2017-11-29    10        6
23039               오리엔트 특급 살인  20178581  2017-11-29     3      629
23060                  반드시 잡는다  20161762  2017-11-29     4      557
23075               어쌔신: 더 비기닝  20173693  2017-12-07     4      493
23082                      강철비  20170402  2017-12-14     9       17
23099            스타워즈: 라스트 제다이  20170443  2017-12-14     2     1107
23112                신과함께-죄와 벌  20150976  2017-12-20     7       34
23122                   위대한 쇼맨  20179462  2017-12-20     3      649

         salesAmt  salesShare  audiCnt  showCnt  searchDay  NationAtt  \
0      1062569500        18.8   161052     1682 2008-01-01          1
21      827405500        14.7   123779     1168 2008-01-01          1
37      497751500         8.8    73572     1553 2008-01-01          0
53      428237000         7.6    61740      811 2008-01-01          0
62      349718000         6.2    49842     1061 2008-01-01          1
71      320816500         5.7    47398      476 2008-01-01          1
80      311429000        18.0    52845     1089 2008-01-03          1
110     665088500        30.8   108071     2042 2008-01-10          0
152     526116500        24.4    81244     1774 2008-01-10          0
179     245547500        11.4    38391     1100 2008-01-10          1
197     153654000         7.1    24385     1425 2008-01-10          1
217     367311000        18.0    56221     1360 2008-01-17          1
233     286317500        14.1    45365     1507 2008-01-17          0
247     379910500        21.2    59123     1917 2008-01-24          1
261     459184501        23.3    72292     1590 2008-01-31          0
282     298557500        15.1    46803     2050 2008-01-31          0
296     144280000         7.3    22361     1203 2008-01-31          2
310     592564500        25.2    91943     1782 2008-02-05          0
333     117044000         5.0    18582     1473 2008-02-05          0
342      14574000         1.3     2082        6 2008-02-12          1
371     722726500        26.3   113673     2032 2008-02-14          0
454     154436500         5.6    23559     1120 2008-02-14          1
477     265263000        14.6    47833     1339 2008-02-21          2
491     411076500        19.3    66132     1595 2008-02-28          0
519     116604500         8.8    18026     1157 2008-03-06          1
533     113996500         8.6    17846     1249 2008-03-06          0
547      44784000         3.4    11196       59 2008-03-06          1
576     430115500        35.4    70632     2094 2008-03-13          1
598     142128500        10.9    22105      719 2008-03-20          1
627      18642000         1.9     3092       15 2008-03-24          2
...           ...         ...      ...      ...        ...        ...
22495   163448800         5.0    27662     1857 2017-09-02          1
22502  1070193300        38.6   143580     4340 2017-09-09          0
22529   607948000        21.9    76925     3191 2017-09-09          1
22549    61048000         2.2     7414       32 2017-09-09          0
22591   237697000        13.5    30803     1740 2017-09-16          2
22611   359380500        18.7    49188     2899 2017-09-17          1
22624    32200000         2.2     4025       13 2017-09-22          1
22685    30010000         2.3     3680       19 2017-09-28          0
22721  3056786300        72.9   481948     7621 2017-09-30          1
22749   101636000         0.8    11660      153 2017-10-09          1
22765    22902000         1.0     2895        9 2017-10-13          0
22773    16540000         0.6     2351        9 2017-10-15          0
22799    15394800         0.5     1803       12 2017-10-17          0
22816   699873800        28.3    87805     3353 2017-10-22          1
22833  2590457400        64.0   415741     7965 2017-10-28          1
22876   420845300        15.3    57510     2581 2017-11-05          2
22889    16774000         0.9     2098        7 2017-11-09          0
22897   341139800        17.0    45059     2230 2017-11-11          1
22926    90017700         4.2    13267     1149 2017-11-12          0
22945    46535500         2.8     5463       17 2017-11-17          0
22979  1246482600        41.2   153553     4132 2017-11-18          1
23001   407772400        13.5    55985     2762 2017-11-18          0
23015     8760000         0.5     1752        7 2017-12-01          0
23039   556848900        17.7    94340     2485 2017-12-02          1
23060   355845700        11.3    59907     2591 2017-12-02          0
23075   229981200        10.8    31793     2092 2017-12-10          1
23082    37640000         2.3     4705       18 2017-12-15          0
23099   966980200        27.5   115246     4313 2017-12-17          1
23112    63287200         1.8     7906       35 2017-12-17          0
23122   306750400         6.5    40995     2736 2017-12-23          1

       RatingAtt  openDt_season  openDt_peak
0              3              3          1.0
21             0              3          1.0
37             1              3          1.0
53             2              3          1.0
62             1              3          1.0
71             3              2          2.0
80             3              3          1.0
110            3              3          1.0
152            1              3          1.0
179            1              3          1.0
197            3              3          1.0
217            2              3          1.0
233            1              3          1.0
247            1              3          1.0
261            1              3          1.0
282            3              3          1.0
296            2              3          1.0
310            1              3          1.0
333            1              3          1.0
342            1              3          1.0
371            2              3          1.0
454            3              3          1.0
477            1              3          1.0
491            0              3          1.0
519            1              0          2.0
533            1              0          2.0
547            0              0          2.0
576            1              0          2.0
598            1              0          2.0
627            1              0          2.0
...          ...            ...          ...
22495          2              1          0.0
22502          1              2          0.0
22529          1              2          0.0
22549          0              2          0.0
22591          1              2          0.0
22611          1              2          0.0
22624          2              2          2.0
22685          1              2          2.0
22721          2              2          0.0
22749          1              2          2.0
22765          1              2          2.0
22773          0              2          2.0
22799          0              2          2.0
22816          0              2          2.0
22833          0              2          2.0
22876          3              3          NaN
22889          2              2          2.0
22897          1              2          2.0
22926          0              2          2.0
22945          3              3          NaN
22979          0              2          2.0
23001          1              2          2.0
23015          1              2          2.0
23039          0              2          2.0
23060          1              2          2.0
23075          1              3          1.0
23082          1              3          1.0
23099          0              3          1.0
23112          0              3          1.0
23122          0              3          1.0

[871 rows x 14 columns]>

In [4]:
df_dataset2

,movieNm,movieCd,openDt_x,rank,scrnCnt,salesAmt,salesShare,audiCnt,showCnt,searchDay,Nation,openDt_y,openDt_season,openDt_peak
0,기다리다 미쳐,20070661,2008-01-01,3,238,497751500,8.8,73572,1553,20080101,0,2008-01-01,4,0
1,P.S. 아이 러브 유,20071003,2008-01-03,6,184,349718000,6.2,49842,1061,20080101,1,2008-01-03,4,0
2,내 사랑,20070639,2007-12-18,6,162,99184500,5.8,15200,649,20080102,1,2007-12-18,4,0
3,꿀벌대소동,20070563,2008-01-03,1,208,311429000,18.0,52845,1089,20080103,1,2008-01-03,4,0
4,헨젤과 그레텔,20070643,2007-12-27,10,168,144407000,3.3,22994,565,20080105,1,2007-12-27,4,0
5,우리 생애 최고의 순간,20070382,2008-01-10,1,379,665088500,30.8,108071,2042,20080110,0,2008-01-10,4,0
6,무방비도시,20071064,2008-01-10,2,296,526116500,24.4,81244,1774,20080110,0,2008-01-10,4,0
7,미스트,20071042,2008-01-10,3,188,245547500,11.4,38391,1100,20080110,1,2008-01-10,4,0
8,마법에 걸린 사랑,20070566,2008-01-10,5,239,153654000,7.1,24385,1425,20080110,1,2008-01-10,4,0
9,써티 데이즈 오브 나이트,20071065,2008-01-10,7,119,51031500,2.4,7804,558,20080110,1,2008-01-10,4,0
10,더 재킷,20071063,2008-01-10,8,146,49581500,2.3,7756,689,20080110,1,2008-01-10,4,0
11,스위니 토드 : 어느 잔혹한 이발사 이야기,20080009,2008-01-17,2,224,367311000,18.0,56221,1360,20080117,1,2008-01-17,4,0
12,뜨거운 것이 좋아,20070660,2008-01-17,4,229,286317500,14.1,45365,1507,20080117,0,2008-01-17,4,0
13,에이리언 VS 프레데터2,20080010,2008-01-17,5,142,161708000,7.9,25598,1076,20080117,1,2008-01-17,4,0
14,엘라의 모험 : 해피엔딩의 위기,20071014,2008-01-24,8,13,46112000,2.3,11528,59,20080117,1,2008-01-24,4,0
15,어린 왕자,20080008,2008-01-17,10,169,48833500,2.4,8004,958,20080117,0,2008-01-17,4,0
16,말할 수 없는 비밀,20071066,2008-01-10,10,25,11917500,0.7,1904,88,20080121,1,2008-01-10,4,0
17,클로버필드,20070672,2008-01-24,2,259,379910500,21.2,59123,1917,20080124,1,2008-01-24,4,0
18,원스어폰어타임,20080011,2008-01-31,7,17,52008000,2.9,12400,63,20080124,0,2008-01-31,4,0
19,에반게리온 : 서(序),20080017,2008-01-24,10,18,37976500,2.1,6235,125,20080124,1,2008-01-24,4,0
20,더 게임,20071675,2008-01-30,1,266,459184501,23.3,72292,1590,20080131,0,2008-01-30,4,0
21,슈퍼맨이었던 사나이,20071067,2008-01-31,3,349,298557500,15.1,46803,2050,20080131,0,2008-01-31,4,0
22,명장,20080013,2008-01-30,5,227,144280000,7.3,22361,1203,20080131,1,2008-01-30,4,0
23,라듸오 데이즈,20080015,2008-01-31,6,246,112421000,5.7,17852,1348,20080131,0,2008-01-31,4,0
24,찰리윌슨의 전쟁,20080021,2008-02-06,9,12,44784000,2.3,11196,57,20080131,1,2008-02-06,4,0
25,6년째 연애중,20070548,2008-02-05,1,289,592564500,25.2,91943,1782,20080205,0,2008-02-05,4,0
26,마지막 선물,20080014,2008-02-05,7,250,117044000,5.0,18582,1473,20080205,0,2008-02-05,4,0
27,점퍼,20080047,2008-02-14,10,6,14574000,1.3,2082,6,20080212,1,2008-02-14,4,0
28,어톤먼트,20080065,2008-02-21,10,9,13727000,1.3,1961,9,20080213,1,2008-02-21,4,0
29,추격자,20080046,2008-02-14,2,391,722726500,26.3,113673,2032,20080214,0,2008-02-14,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2176,저스티스 리그,20168221,2017-11-15,1,1192,1246482600,41.2,153553,4132,20171114,1,2017-11-15,3,1
2177,7호실,20168754,2017-11-15,3,629,407772400,13.5,55985,2762,20171114,0,2017-11-15,3,1
2178,페이트 스테이 나이트 헤븐즈필 제1장 프레시지 플라워,20175611,2017-11-16,7,167,67408200,2.2,9271,366,20171115,1,2017-11-16,3,1
2179,키드냅,20174222,2017-11-22,9,153,26200800,1.0,3615,675,20171121,1,2017-11-22,3,1
2180,역모-반란의 시대,20173903,2017-11-23,6,349,40740400,1.5,5727,777,20171122,0,2017-11-23,3,1
2181,하이큐!! 재능과 센스,20174778,2017-11-15,9,78,26599500,1.0,3935,120,20171122,1,2017-11-15,3,1
2182,래빗 스쿨,20175223,2017-11-23,6,302,91099200,1.4,12343,443,20171124,1,2017-11-23,3,1
2183,피터와 모글리의 크리스마스 어드벤처,20175288,2017-11-23,8,250,61611800,1.0,8244,353,20171124,1,2017-11-23,3,1
2184,기억의 밤,20173581,2017-11-29,10,6,8760000,0.5,1752,7,20171126,0,2017-11-29,3,1
2185,오리엔트 특급 살인,20178581,2017-11-29,3,629,556848900,17.7,94340,2485,20171128,1,2017-11-29,3,1
2186,반드시 잡는다,20161762,2017-11-29,4,557,355845700,11.3,59907,2591,20171128,0,2017-11-29,3,1
2187,빅 배드 폭스,20174073,2017-11-30,10,219,47454100,0.8,6085,284,20171202,1,2017-11-30,3,1
2188,산상수훈,20170272,2017-12-07,10,3,5865000,0.3,1079,3,20171203,0,2017-12-07,4,0
2189,은혼,20175903,2017-12-07,10,5,12993500,0.8,1599,6,20171205,1,2017-12-07,4,0
2190,메리와 마녀의 꽃,20174585,2017-12-07,3,562,293485000,13.8,40101,2186,20171206,1,2017-12-07,4,0
2191,어쌔신: 더 비기닝,20173693,2017-12-07,4,493,229981200,10.8,31793,2092,20171206,1,2017-12-07,4,0
2192,뽀로로 극장판 공룡섬 대모험,20174846,2017-12-07,6,468,143674000,6.7,20700,701,20171206,0,2017-12-07,4,0
2193,강철비,20170402,2017-12-14,9,17,37640000,2.3,4705,18,20171210,0,2017-12-14,4,0
2194,스타워즈: 라스트 제다이,20170443,2017-12-14,2,1107,966980200,27.5,115246,4313,20171213,1,2017-12-14,4,0
2195,신과함께-죄와 벌,20150976,2017-12-20,7,34,63287200,1.8,7906,35,20171213,0,2017-12-20,4,0
2196,튤립 피버,20175481,2017-12-14,8,357,57373500,1.6,7731,781,20171213,1,2017-12-14,4,0
2197,극장판 숲의 요정 페어리루 ~크리스마스의 기적: 마법의 날개~,20176367,2017-12-14,10,147,23251900,0.7,3383,200,20171213,1,2017-12-14,4,0
2198,1987,20170590,2017-12-27,6,45,82853000,3.1,9755,45,20171218,0,2017-12-27,4,0
2199,위대한 쇼맨,20179462,2017-12-20,3,649,306750400,6.5,40995,2736,20171219,1,2017-12-20,4,0
2200,극장판 포켓몬스터 너로 정했다!,20174965,2017-12-21,5,424,101868900,2.1,14583,561,20171220,1,2017-12-21,4,0
2201,몬스터 패밀리,20176082,2017-12-21,6,381,74273100,1.5,12201,488,20171220,1,2017-12-21,4,0
2202,더 크리스마스,20176022,2017-12-21,9,114,25972100,0.5,4525,132,20171220,1,2017-12-21,4,0
2203,패터슨,20176049,2017-12-21,10,59,15468900,0.2,1868,102,20171221,1,2017-12-21,4,0
2204,원더,20176947,2017-12-27,5,161,79340700,1.3,12864,666,20171226,1,2017-12-27,4,0
2205,극장판 프리파라 모두의 동경♪ 렛츠고☆프리파리,20177479,2017-12-28,9,150,57539500,1.0,8122,234,20171227,1,2017-12-28,4,0

In [5]:
df_nation = pd.read_excel('./data/국적비교.xlsx')
df_nation

,rank,movieNm,openDt,sales,salesShare,salesAmt,audiCnt,audiCntAnt,scrnCnt,showCnt,Nation,Nation2,Maker,Company,Rate,Genre,director,actor
0,1,"좋은 놈, 나쁜 놈, 이상한 놈",2008-07-17,43747552000,0.046,43747552000,6684933,6684933,824,93477,한국,한국,"(주)다크서클픽쳐스,(주)바른손이앤에이",씨제이엔터테인먼트,15세이상관람가,"서부극(웨스턴),액션,어드벤처",김지운,"송강호,이병헌,정우성,오달수,엄지원,김광일,손병호,이청아,김선영,성정훈,송승현,신상..."
1,2,추격자,2008-02-14,33986959000,0.035,33986959000,5046096,5046096,433,106805,한국,한국,(주)영화사비단길,(주)쇼박스,청소년관람불가,"범죄,스릴러,액션",나홍진,"김윤석,하정우,서영희,박효주,김유정,최정우,정인기,최지윤,김은성,최홍석,박지안,박진..."
2,3,쿵푸 팬더,2008-06-05,29996476000,0.031,29996476000,4653929,4653929,563,79850,미국,미국,NaN,씨제이엔터테인먼트,전체관람가,"애니메이션,코미디,액션,가족","마크 오스본,존 스티븐슨","더스틴 호프만,루시 루,잭 블랙,안젤리나 졸리,성룡,김기현"
3,4,맘마미아!,2008-09-03,29571255750,0.031,29571255750,4552475,4552475,451,111024,미국,미국,NaN,유니버설픽쳐스인터내셔널 코리아(유),12세이상관람가,"멜로/로맨스,뮤지컬",필리다 로이드,"아만다 사이프리드,메릴 스트립,콜린 퍼스"
4,5,과속스캔들,2008-12-03,28506879500,0.030,28506879500,4361509,4361509,408,62296,한국,한국,"(주)토일렛픽쳐스,(주)디씨지플러스",롯데쇼핑㈜롯데엔터테인먼트,12세이상관람가,코미디,강형철,"차태현,박보영,왕석현,임지규,황우슬혜,정원중,김기방,김혜진,노수정,류수경,김준호,문..."
5,6,강철중: 공공의 적 1-1,2008-06-19,28638460100,0.030,28638460100,4313101,4313101,707,74157,한국,한국,"(주)시네마서비스글로벌,(주)시네마서비스","씨제이엔터테인먼트,(주)시네마서비스",15세이상관람가,"드라마,액션",강우석,"설경구,정재영,강신일,유해진,탁트인,이상현,김윤성,이재원,조한영,박창용,박태훈,김건..."
6,7,아이언맨,2008-04-30,27798047000,0.029,27798047000,4290816,4290816,592,77942,미국,미국,NaN,씨제이엔터테인먼트,12세이상관람가,"SF,드라마,액션",존 파브로,"로버트 다우니 주니어,테렌스 하워드,제프 브리지스,기네스 팰트로우"
7,8,인디아나 존스 4 : 크리스탈 해골의 왕국,2008-05-22,26689440000,0.028,26689440000,4111753,4111753,771,75393,미국,미국,NaN,씨제이엔터테인먼트,12세이상관람가,"액션,어드벤처",스티븐 스필버그,"해리슨 포드,샤이아 라보프"
8,9,미이라 3:황제의 무덤,2008-07-30,26217311000,0.027,26217311000,4090885,4090885,634,64779,미국,미국,NaN,유니버설픽쳐스인터내셔널 코리아(유),12세이상관람가,"액션,어드벤처,판타지",롭 코헨,"브렌든 프레이저,마리아 벨로,이연걸"
9,10,다크 나이트,2008-08-06,26878184500,0.028,26878184500,4060490,4060490,462,63561,미국,미국,NaN,"주식회사 해리슨앤컴퍼니,워너브러더스 코리아(주)",15세이상관람가,"범죄,드라마,액션,미스터리",크리스토퍼 놀란,"크리스찬 베일,마이클 케인,히스 레저,아론 에크하트,매기 질렌할,게리 올드만,모건 프리먼"
10,11,우리 생애 최고의 순간,2008-01-10,26113394000,0.027,26119898000,4018059,4018872,418,70721,한국,한국,(주)엠케이픽처스,(주)싸이더스,전체관람가,드라마,임순례,"문소리,김정은,엄태웅,김지영,조은지,이미도,조영진,이봉규,정석용,하정우,정세형,김종..."
11,12,신기전,2008-09-04,24326353000,0.025,24326353000,3728430,3728430,585,78462,한국,한국,(주)시네마서비스글로벌,씨제이엔터테인먼트,15세이상관람가,"사극,드라마,액션,전쟁",김유진,"정재영,한은정,안성기,허준호,김명수,신정근,조원희,이광희,박윤희,조주현,최만수,박보..."
12,13,원티드,2008-06-26,19249245000,0.020,19249245000,2858720,2858720,512,55001,미국,미국,NaN,유니버설픽쳐스인터내셔널 코리아(유),청소년관람불가,"스릴러,액션",티무르 베크맘베토브,"제임스 맥어보이,안젤리나 졸리,모건 프리먼"
13,14,핸콕,2008-07-02,17844690500,0.019,17844690500,2722574,2722574,602,60236,미국,미국,NaN,한국소니픽쳐스릴리징브에나비스타영화㈜,12세이상관람가,"액션,드라마,코미디",피터 버그,"윌 스미스,샤를리즈 테론"
14,15,테이큰,2008-04-09,15971449000,0.017,15971449000,2359061,2359061,256,60944,프랑스,프랑스,NaN,㈜스튜디오이쩜영,청소년관람불가,"범죄,스릴러,액션",피에르 모렐,"리암 니슨,매기 그레이스"
15,16,미인도,2008-11-13,15652272500,0.016,15652272500,2341521,2341521,450,69444,한국,한국,"㈜이룸영화사,(주)영화사참",씨제이엔터테인먼트,청소년관람불가,"사극,드라마,멜로/로맨스",전윤수,"김민선,김영호,김남길,추자현,한명구,이성훈,강민호,박예슬,박용,김형수,신주희,황선환..."
16,17,이글 아이,2008-10-09,14869812500,0.015,14869812500,2292172,2292172,407,59132,미국,미국,NaN,씨제이엔터테인먼트,12세이상관람가,"액션,스릴러,미스터리",D.J. 카루소,"샤이아 라보프,미셸 모나한,도니 제프콧"
17,18,007 퀀텀 오브 솔러스,2008-11-05,14389307000,0.015,14389307000,2205159,2205159,520,70774,미국,미국,NaN,한국소니픽쳐스릴리징브에나비스타영화㈜,15세이상관람가,"액션,어드벤처",마크 포스터,"다니엘 크레이그,올가 큐리렌코,매티유 아맬릭"
18,19,눈에는 눈 이에는 이,2008-07-31,13410811500,0.014,13410811500,2058616,2058616,445,46474,한국,한국,(주)태원엔터테인먼트,롯데쇼핑㈜롯데엔터테인먼트,15세이상관람가,"범죄,스릴러,액션","곽경택,안권태","한석규,차승원,송영창,김윤태,이병준,김혜정,박영찬,홍의정,최지혜,임성규,신창수,박정..."
19,20,아내가 결혼했다,2008-10-23,12062180000,0.013,12062180000,1799447,1799447,417,57496,한국,한국,(주)주피터필름,씨제이엔터테인먼트,청소년관람불가,"멜로/로맨스,드라마",정윤수,"손예진,김주혁,주상욱,이주실,천성훈,오정세,김병춘,정세형"
20,21,님은 먼 곳에,2008-07-24,11205439000,0.012,11205439000,1706037,1706037,499,36555,한국,"한국,태국",(주)타이거픽쳐스,(주)쇼박스,15세이상관람가,"드라마,전쟁",이준익,"수애,정진영,정경호,주진모,조미령,홍영승,한성수,릭키 준,서성만,장재욱,이홍복,김장..."
21,22,점퍼,2008-02-14,10943088000,0.011,10943088000,1665268,1665268,350,43335,미국,미국,NaN,이십세기폭스필름코퍼레이션,15세이상관람가,"SF,드라마,어드벤처",더그 라이만,"레이첼 빌슨,헤이든 크리스텐슨,제이미 벨"
22,23,고死 : 피의 중간고사,2008-08-07,10300791000,0.011,10300791000,1634192,1634192,270,42719,한국,한국,"(주)코어콘텐츠미디어,(주)워터앤트리",에스케이텔레콤(주),15세이상관람가,"공포(호러),스릴러",창,"이범수,남규리,김범,박우람,조기원,김형진,권현상,진성,백하나,이효연,윤정희,양지원,..."
23,24,무방비도시,2008-01-10,10591149500,0.011,10591149500,1600856,1600856,336,38306,한국,한국,쌈지아이비젼영상사업단,씨제이엔터테인먼트,15세이상관람가,"범죄,액션",이상기,"김명민,손예진,김해숙,김준배,김정태,홍의정,신창수,김병옥,박종희,심민섭,박찬형,황혜..."
24,25,적벽대전:거대한 전쟁의 시작,2008-07-10,10192112500,0.011,10192112500,1570703,1570703,447,32719,중국,중국,NaN,(주)쇼박스,15세이상관람가,"액션,드라마,전쟁",오우삼,"양조위,금성무,장첸,나카무라 시도,호군,장풍의,조미,즈링 린/임지령"
25,26,원스어폰어타임,2008-01-31,10136738500,0.011,10136738500,1544486,1544486,314,37679,한국,한국,윈엔터테인먼트,(유)씨에이치엔터테인먼트,12세이상관람가,"액션,코미디","정용기,이현석","박용우,서민균,이보영,심호성,김수현,김응수,성동일,강규영,강동원,신성식,김은혜,박현..."
26,27,더 게임,2008-01-30,9807963501,0.010,9807963501,1479859,1479859,338,31877,한국,한국,(주)프라임엔터테인먼트,NaN,15세이상관람가,스릴러,윤인호,"변희봉,손현주,신하균,이혜영,김혁,노승범,박유리,김효배,박유리,차승환,김석현,유영권..."
27,28,나니아 연대기:캐스피언 왕자,2008-05-15,9236619000,0.010,9236619000,1468903,1468903,604,43010,미국,"미국,영국",NaN,한국소니픽쳐스릴리징브에나비스타영화㈜,전체관람가,"어드벤처,가족,판타지",앤드류 아담슨,조지 헨리
28,29,월ㆍE,2008-08-06,8289679500,0.009,8289679500,1325834,1325834,347,32819,미국,미국,NaN,한국소니픽쳐스릴리징브에나비스타영화㈜,전체관람가,"애니메이션,코미디,액션,어드벤처,가족,SF",앤드류 스탠튼,"엘리사 나이트,벤 버트"
29,30,영화는 영화다,2008-09-11,8967253000,0.009,8967253000,1311071,1311071,315,37337,한국,한국,"(주)김기덕 필름,염화미소",㈜스튜디오이쩜영,청소년관람불가,"액션,드라마,범죄",장훈,"소지섭,강지환,홍수현,고창석,허태희,김태웅,곽희원,박상진,김소리,임석규,윤정진,오호..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29280,4652,반지의 비밀일기,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,애니메이션,NaN,NaN
29281,4652,백 프롬 더 비트,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,드라마,NaN,김시은
29283,4652,사랑에 빠지다,NaT,0,0.000,0,0,0,1,5,기타,기타,NaN,NaN,NaN,기타,NaN,NaN
29286,4652,살롱 데 르퓌제 1 - 2017 전북독립영화제,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,기타,NaN,NaN
29287,4652,살롱 데 르퓌제 2 - 2017 전북독립영화제,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,기타,NaN,NaN
29290,4652,샤워,NaT,0,0.000,0,0,0,1,2,중국,중국,NaN,NaN,NaN,코미디,장양,"강무,주욱"
29294,4652,셜록 주니어,NaT,0,0.000,0,0,0,1,1,미국,미국,NaN,NaN,NaN,"코미디,판타지",버스터 키튼,NaN
29298,4652,순다르반스,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,다큐멘터리,박환성,NaN
29301,4652,시민참여섹션1 '시대난민' - 2017 FALLing in JEONJU,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,기타,NaN,NaN
29302,4652,시민참여섹션2 '무주공산' - 2017 FALLing in JEONJU,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,기타,NaN,NaN
29303,4652,시월애,2000-09-09,0,0.000,200000,0,40,1,2,한국,한국,㈜싸이더스픽쳐스,브에나비스타인터내셔널코리아,12세관람가,"멜로/로맨스,판타지",이현승,"이정재,전지현,김무생,조승연,이인철,김미현,최윤영,정석원,김지무"
29304,4652,신원불상,NaT,0,0.000,0,0,0,1,2,이란,이란,NaN,NaN,NaN,드라마,NaN,NaN
29308,4652,아리랑 2,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,드라마,나운규,NaN
29310,4652,아이 엠 썸바디,NaT,0,0.000,0,0,0,1,2,중국,"중국,홍콩",NaN,NaN,NaN,"드라마,코미디",이동승,NaN
29311,4652,아인쉬타인과 아인쉬타인,NaT,0,0.000,0,0,0,1,2,중국,중국,NaN,NaN,NaN,NaN,NaN,NaN
29315,4652,"안녕, 전우치 스페셜",NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,애니메이션,김대창,NaN
29318,4652,어둔 밤,2018-09-06,0,0.000,0,0,0,1,1,한국,한국,풋메이드 픽쳐스,(주)영화사오원,15세이상관람가,"액션,코미디",심찬양,"송의성,이요셉,김상훈,오수경"
29319,4652,언브라이들,NaT,0,0.000,0,0,0,1,1,미국,미국,NaN,NaN,NaN,기타,NaN,NaN
29320,4652,열일작심,NaT,0,0.000,0,0,0,1,1,중국,중국,NaN,NaN,NaN,"드라마,액션,범죄",NaN,NaN
29323,4652,우리생에 최고의 날,NaT,0,0.000,0,0,0,1,5,기타,기타,NaN,NaN,NaN,기타,NaN,NaN
29327,4652,이미지워크숍 2017,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,기타,NaN,NaN
29328,4652,이올란타 & 호두까기인형,NaT,0,0.000,0,0,0,10,47,프랑스,프랑스,NaN,에스디시코리아 주식회사,전체관람가,공연,드미트리 체르니아코프,"알렉산더 침발류크,소냐 욘체바"
29330,4652,입시충,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,다큐멘터리,김재우,NaN
29340,4652,지역초청 - 2017 전북독립영화제,NaT,0,0.000,0,0,0,1,1,한국,한국,NaN,NaN,NaN,기타,NaN,NaN
29341,4652,집으로 가는길,2000-11-04,0,0.000,0,0,0,1,2,중국,중국,NaN,NaN,12세관람가,드라마,장예모,"장쯔이,손홍뢰"
29343,4652,책상 서랍 속의 동화,1999-10-30,0,0.000,0,0,0,1,2,중국,중국,"콜럼비아 픽쳐스 코포레이션,구앙시필름즈튜디오",NaN,전체관람가,드라마,장예모,"장휘거,웨이 민치,티안 젠다"
29346,4652,천리주단기,2006-07-20,0,0.000,11042000,0,1613,1,2,중국,"중국,일본",NaN,소니픽쳐스릴리징코리아,전체관람가,드라마,장예모,다카쿠라 켄
29352,4652,태양은 없다,1999-01-01,0,0.000,0,0,0,1,2,한국,한국,(주)우노필름,NaN,18세 미만인 자는 관람할 수 없는 등급,"드라마,액션",김성수,"정우성,문소연,박지훈,이정재,이범수,한고은,박성웅,이기열,이봉규"
29355,4652,페르쇼가의 장남,NaT,0,0.000,0,0,0,1,1,프랑스,"프랑스,이탈리아",NaN,NaN,NaN,기타,장 피에르 멜빌,NaN
29358,4652,학과 함께 날다,NaT,0,0.000,0,0,0,1,2,중국,중국,NaN,NaN,NaN,드라마,리루이쥔,NaN

In [16]:
df_a = pd.merge(df_nation, df_dataset2, on=('movieNm'))
df_a = df_a.drop_duplicates('movieNm', keep='first')
df_a

,rank_x,movieNm,openDt,sales,salesShare_x,salesAmt_x,audiCnt_x,audiCntAnt,scrnCnt_x,showCnt_x,...,scrnCnt_y,salesAmt_y,salesShare_y,audiCnt_y,showCnt_y,searchDay,Nation_y,openDt_y,openDt_season,openDt_peak
0,2,추격자,2008-02-14,33986959000,0.035,33986959000,5046096,5046096,433,106805,...,391,722726500,26.3,113673,2032,20080214,0,2008-02-14,4,0
1,3,쿵푸 팬더,2008-06-05,29996476000,0.031,29996476000,4653929,4653929,563,79850,...,446,680312000,30.3,105337,2790,20080605,1,2008-06-05,2,1
2,4,맘마미아!,2008-09-03,29571255750,0.031,29571255750,4552475,4552475,451,111024,...,16,46296000,4.0,11574,58,20080828,1,2008-09-03,3,0
3,5,과속스캔들,2008-12-03,28506879500,0.030,28506879500,4361509,4361509,408,62296,...,25,18924000,1.6,4731,25,20081124,0,2008-12-03,4,0
4,6,강철중: 공공의 적 1-1,2008-06-19,28638460100,0.030,28638460100,4313101,4313101,707,74157,...,348,367756500,24.1,55080,852,20080618,0,2008-06-19,2,1
5,7,아이언맨,2008-04-30,27798047000,0.029,27798047000,4290816,4290816,592,77942,...,496,977191000,46.7,152797,2823,20080430,1,2008-04-30,1,1
6,8,인디아나 존스 4 : 크리스탈 해골의 왕국,2008-05-22,26689440000,0.028,26689440000,4111753,4111753,771,75393,...,6,8778000,1.1,1254,6,20080520,1,2008-05-22,1,1
7,9,미이라 3:황제의 무덤,2008-07-30,26217311000,0.027,26217311000,4090885,4090885,634,64779,...,496,1884901000,47.0,297855,3168,20080730,1,2008-07-30,2,0
8,10,다크 나이트,2008-08-06,26878184500,0.028,26878184500,4060490,4060490,462,63561,...,316,403663000,12.0,59957,795,20080805,1,2008-08-06,2,0
9,11,우리 생애 최고의 순간,2008-01-10,26113394000,0.027,26119898000,4018059,4018872,418,70721,...,379,665088500,30.8,108071,2042,20080110,0,2008-01-10,4,0
10,12,신기전,2008-09-04,24326353000,0.025,24326353000,3728430,3728430,585,78462,...,7,13832000,0.4,1976,9,20080807,0,2008-09-04,3,0
11,13,원티드,2008-06-26,19249245000,0.020,19249245000,2858720,2858720,512,55001,...,20,25760000,1.3,3680,20,20080624,1,2008-06-26,2,1
12,14,핸콕,2008-07-02,17844690500,0.019,17844690500,2722574,2722574,602,60236,...,526,1092852000,44.7,167724,3404,20080702,1,2008-07-02,2,0
13,15,테이큰,2008-04-09,15971449000,0.017,15971449000,2359061,2359061,256,60944,...,214,624445500,16.4,89502,1498,20080409,1,2008-04-09,1,1
14,16,미인도,2008-11-13,15652272500,0.016,15652272500,2341521,2341521,450,69444,...,419,641160000,31.1,103818,2446,20081113,0,2008-11-13,3,1
15,17,이글 아이,2008-10-09,14869812500,0.015,14869812500,2292172,2292172,407,59132,...,312,524374000,40.2,86957,1815,20081009,1,2008-10-09,3,1
16,18,007 퀀텀 오브 솔러스,2008-11-05,14389307000,0.015,14389307000,2205159,2205159,520,70774,...,454,630792500,51.5,100124,2734,20081105,1,2008-11-05,3,1
17,19,눈에는 눈 이에는 이,2008-07-31,13410811500,0.014,13410811500,2058616,2058616,445,46474,...,7,7025000,0.4,1662,8,20080715,0,2008-07-31,2,0
18,20,아내가 결혼했다,2008-10-23,12062180000,0.013,12062180000,1799447,1799447,417,57496,...,400,594061000,39.6,96014,2066,20081023,0,2008-10-23,3,1
19,21,님은 먼 곳에,2008-07-24,11205439000,0.012,11205439000,1706037,1706037,499,36555,...,19,32486000,2.0,4810,19,20080714,1,2008-07-24,2,0
20,22,점퍼,2008-02-14,10943088000,0.011,10943088000,1665268,1665268,350,43335,...,6,14574000,1.3,2082,6,20080212,1,2008-02-14,4,0
21,23,고死 : 피의 중간고사,2008-08-07,10300791000,0.011,10300791000,1634192,1634192,270,42719,...,16,46874000,1.0,11574,58,20080731,0,2008-08-07,2,0
22,24,무방비도시,2008-01-10,10591149500,0.011,10591149500,1600856,1600856,336,38306,...,296,526116500,24.4,81244,1774,20080110,0,2008-01-10,4,0
23,25,적벽대전:거대한 전쟁의 시작,2008-07-10,10192112500,0.011,10192112500,1570703,1570703,447,32719,...,6,7450000,0.3,1490,7,20080703,1,2008-07-10,2,0
24,26,원스어폰어타임,2008-01-31,10136738500,0.011,10136738500,1544486,1544486,314,37679,...,17,52008000,2.9,12400,63,20080124,0,2008-01-31,4,0
25,27,더 게임,2008-01-30,9807963501,0.010,9807963501,1479859,1479859,338,31877,...,266,459184501,23.3,72292,1590,20080131,0,2008-01-30,4,0
26,29,월ㆍE,2008-08-06,8289679500,0.009,8289679500,1325834,1325834,347,32819,...,51,20831500,0.6,3095,52,20080805,1,2008-08-06,2,0
27,30,영화는 영화다,2008-09-11,8967253000,0.009,8967253000,1311071,1311071,315,37337,...,240,111830000,10.4,16579,746,20080910,0,2008-09-11,3,0
28,31,지구가 멈추는 날,2008-12-24,8582183500,0.009,8582183500,1307068,1307068,469,22590,...,413,434792000,22.5,67707,2485,20081223,1,2008-12-24,4,0
29,32,트와일라잇,2008-12-10,8369922000,0.009,8369922000,1292332,1292332,345,28082,...,17,46292000,3.7,11573,60,20081204,1,2008-12-10,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,253,내게 남은 사랑을,2017-11-02,180693600,0.000,180693600,27414,27414,156,1656,...,9,17156000,0.8,2232,9,20171030,0,2017-11-02,3,1
2145,254,지니어스,2017-04-13,209700437,0.000,209700437,27224,27224,172,2310,...,167,21148400,1.0,2955,293,20170412,1,2017-04-13,1,1
2146,255,로스트 인 파리,2017-05-18,215591038,0.000,215591038,27206,27206,85,1708,...,81,12418600,0.3,1532,126,20170518,1,2017-05-18,1,1
2147,257,몬스터 섬의 비밀,2017-09-07,184568800,0.000,184568800,26739,26739,150,1736,...,147,46650800,0.7,6104,260,20170909,1,2017-09-07,3,0
2148,258,아기돼지 3형제와 매직램프,2017-03-23,208444600,0.000,208444600,26670,26670,135,1388,...,129,45994500,0.5,5772,184,20170324,1,2017-03-23,1,1
2149,259,메소드,2017-11-02,215611800,0.000,215611800,26577,26577,244,2933,...,238,21924900,0.8,2857,399,20171101,0,2017-11-02,3,1
2150,261,배저로와 친구들: 신비한 모험,2017-10-26,177884400,0.000,177884400,26185,26185,293,1758,...,287,48890700,0.6,6840,376,20171027,1,2017-10-26,3,1
2151,262,슈퍼 버드,2017-04-06,183154100,0.000,183154100,25964,25964,288,1858,...,288,49484100,1.1,6629,405,20170407,1,2017-04-06,1,1
2152,263,부니베어: 로거빅 컴백홈 프로젝트,2017-06-29,177955300,0.000,177955300,25908,25908,277,1799,...,277,50438200,0.9,6935,392,20170630,1,2017-06-29,2,1
2153,264,골드,2017-03-22,195316900,0.000,195316900,25612,25612,200,3102,...,200,31233800,1.5,4355,485,20170321,1,2017-03-22,1,1
2154,268,아우토반,2017-03-22,196841500,0.000,196841500,24983,24983,153,3489,...,149,26823000,1.3,3707,601,20170321,1,2017-03-22,1,1
2155,278,파워배틀 와치카: 와치가면의 역습,2017-06-01,166656500,0.000,166656500,23630,23630,246,1787,...,163,42720100,0.3,6046,193,20170605,0,2017-06-01,2,1
2156,281,토마스와 친구들: 수수께끼 해적선과 보물찾기,2017-06-29,155824700,0.000,155824700,23395,23395,145,1544,...,113,23512900,0.2,3562,159,20170707,1,2017-06-29,2,1
2157,282,유리정원,2017-10-25,160437700,0.000,160437700,22752,22752,332,4480,...,332,23059000,0.6,3933,627,20171024,0,2017-10-25,3,1
2158,284,송 투 송,2017-07-26,172525100,0.000,172525100,22518,22518,97,1526,...,86,24039800,0.3,3906,147,20170725,1,2017-07-26,2,0
2159,288,극장판 어드벤처 타임: 비밀의 아일랜드,2017-04-13,163679600,0.000,163679600,19986,19986,125,1009,...,124,42994200,0.7,5214,161,20170414,1,2017-04-13,1,1
2160,294,그 후,2017-07-06,142319508,0.000,142319508,18648,18648,168,2451,...,156,15539300,0.4,2170,279,20170705,0,2017-07-06,2,0
2161,295,오즈의 마법사 2,2017-05-03,143173700,0.000,143173700,18535,18535,142,908,...,142,54821600,0.5,7009,182,20170502,1,2017-05-03,1,1
2162,296,은혼,2017-12-07,148853500,0.000,148853500,18323,18323,137,2136,...,5,12993500,0.8,1599,6,20171205,1,2017-12-07,4,0
2163,297,신서유기 : 몽키킹의 부활,2017-11-02,129357400,0.000,129357400,18247,18247,212,1139,...,212,42463300,0.5,5737,293,20171103,1,2017-11-02,3,1
2164,299,배드 지니어스,2017-11-02,141276336,0.000,141276336,17941,17941,200,1983,...,181,8983500,0.5,1248,244,20171105,1,2017-11-02,3,1
2165,307,빅 배드 폭스,2017-11-30,120614100,0.000,120614100,16340,16340,219,1125,...,219,47454100,0.8,6085,284,20171202,1,2017-11-30,3,1
2166,308,링스,2017-04-06,136520300,0.000,136520300,16336,16336,123,1709,...,103,14705500,0.9,1880,155,20170405,1,2017-04-06,1,1
2167,315,콜로설,2017-04-20,114967100,0.000,114967100,14687,14687,305,2964,...,305,24375000,1.6,3367,625,20170419,1,2017-04-20,1,1
2168,319,개구리왕국 2,2017-03-23,99741700,0.000,99741700,14236,14236,171,819,...,171,30011900,0.4,4023,197,20170325,1,2017-03-23,1,1
2169,323,용순,2017-06-08,97538200,0.000,97538200,13268,13268,126,2558,...,117,8979500,0.3,1236,272,20170607,0,2017-06-08,2,1
2170,332,주키퍼스 와이프,2017-10-12,90190446,0.000,90190446,11795,11795,100,1705,...,92,5032000,0.3,705,164,20171015,1,2017-10-12,3,1
2171,363,나의 엔젤,2017-10-12,68315000,0.000,68315000,9097,9097,91,1433,...,80,6498500,0.3,957,162,20171011,1,2017-10-12,3,1
2172,400,베를린 신드롬,2017-07-06,54659800,0.000,54659800,7011,7011,78,844,...,73,7179000,0.2,998,146,20170705,1,2017-07-06,2,0
2173,410,암살교실: 졸업편,2017-04-21,34784500,0.000,34784500,6491,6491,46,245,...,1,13390000,0.4,2678,7,20170530,1,2017-04-21,1,1

In [17]:

Nation_var= []
for idx, a in enumerate(df_a['Nation_x']):
    if type(a) is not str:
        continue
    elif a == '한국':
         Nation_var.append(0)
    elif a == '미국':
         Nation_var.append(1)
    else:
         Nation_var.append(2)
df_a['Nation_att'] = pd.Series(Nation_var)

[0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 2,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 0,
 0,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 2,
 2,
 0,
 2,
 0,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 0,
 2,
 2,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 2,
 2,
 1,
 0,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 2,
 0,
 1,
 2,
 1,
 0,
 0,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 0,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 0,
 2,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 2,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 2,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 2,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 2,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 0,
 1,
 2,
 1,
 0,
 1,
 2,
 2,
 0,
 1,
 1,
 2,
 0,
 1,
 2,
 2,
 1,
 0,
 0,
 2,
 2,
 1,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 1,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 0,
 2,
 1,
 1,
 2,
 0,
 2,
 1,
 2,
 0,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 0,
 2,
 2,
 0,
 2,
 2,
 1,
 2,
 0,
 0,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 2,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 2,
 2,
 2,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 2,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 2,
 0,
 1,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 0,
 2,
 1,
 0,
 2,
 1,
 1,
 0,
 2,
 1,
 0,
 2,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 0,
 2,
 2,
 0,
 1,
 1,
 0,
 2,
 0,
 2,
 1,
 1,
 0,
 0,
 2,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 1,
 2,
 2,
 0,
 2,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 0,
 1,
 0,
 0,
 2,
 1,
 1,
 0,
 2,
 1,
 0,
 0,
 1,
 1,
 2,
 1,
 1,
 0,
 0,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 0,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 2,
 2,
 1,
 2,
 2,
 0,
 0,
 0,
 1,
 1,
 2,
 1,
 0,
 2,
 2,
 2,
 1,
 1,
 0,
 0,
 1,
 1,
 2,
 0,
 1,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 1,
 1,
 0,
 2,
 1,
 0,
 1,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 1,
 1,
 2,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 1,
 1,
 2,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 2,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 2,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 2,
 2,
 1,
 2,
 1,
 0,
 1,
 2,
 2,
 0,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 0,
 1,
 0,
 0,
 2,
 0,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 0,
 2,
 2,
 0,
 1,
 0,
 0,
 2,
 2,
 1,
 1,
 0,
 0,
 2,
 0,
 1,
 ...]

In [18]:
df_a['Nation_att'] = pd.Series(Nation_var)
df_a

,rank_x,movieNm,openDt,sales,salesShare_x,salesAmt_x,audiCnt_x,audiCntAnt,scrnCnt_x,showCnt_x,...,salesAmt_y,salesShare_y,audiCnt_y,showCnt_y,searchDay,Nation_y,openDt_y,openDt_season,openDt_peak,Nation_att
0,2,추격자,2008-02-14,33986959000,0.035,33986959000,5046096,5046096,433,106805,...,722726500,26.3,113673,2032,20080214,0,2008-02-14,4,0,0
1,3,쿵푸 팬더,2008-06-05,29996476000,0.031,29996476000,4653929,4653929,563,79850,...,680312000,30.3,105337,2790,20080605,1,2008-06-05,2,1,1
2,4,맘마미아!,2008-09-03,29571255750,0.031,29571255750,4552475,4552475,451,111024,...,46296000,4.0,11574,58,20080828,1,2008-09-03,3,0,1
3,5,과속스캔들,2008-12-03,28506879500,0.030,28506879500,4361509,4361509,408,62296,...,18924000,1.6,4731,25,20081124,0,2008-12-03,4,0,0
4,6,강철중: 공공의 적 1-1,2008-06-19,28638460100,0.030,28638460100,4313101,4313101,707,74157,...,367756500,24.1,55080,852,20080618,0,2008-06-19,2,1,0
5,7,아이언맨,2008-04-30,27798047000,0.029,27798047000,4290816,4290816,592,77942,...,977191000,46.7,152797,2823,20080430,1,2008-04-30,1,1,1
6,8,인디아나 존스 4 : 크리스탈 해골의 왕국,2008-05-22,26689440000,0.028,26689440000,4111753,4111753,771,75393,...,8778000,1.1,1254,6,20080520,1,2008-05-22,1,1,1
7,9,미이라 3:황제의 무덤,2008-07-30,26217311000,0.027,26217311000,4090885,4090885,634,64779,...,1884901000,47.0,297855,3168,20080730,1,2008-07-30,2,0,1
8,10,다크 나이트,2008-08-06,26878184500,0.028,26878184500,4060490,4060490,462,63561,...,403663000,12.0,59957,795,20080805,1,2008-08-06,2,0,1
9,11,우리 생애 최고의 순간,2008-01-10,26113394000,0.027,26119898000,4018059,4018872,418,70721,...,665088500,30.8,108071,2042,20080110,0,2008-01-10,4,0,0
10,12,신기전,2008-09-04,24326353000,0.025,24326353000,3728430,3728430,585,78462,...,13832000,0.4,1976,9,20080807,0,2008-09-04,3,0,0
11,13,원티드,2008-06-26,19249245000,0.020,19249245000,2858720,2858720,512,55001,...,25760000,1.3,3680,20,20080624,1,2008-06-26,2,1,1
12,14,핸콕,2008-07-02,17844690500,0.019,17844690500,2722574,2722574,602,60236,...,1092852000,44.7,167724,3404,20080702,1,2008-07-02,2,0,1
13,15,테이큰,2008-04-09,15971449000,0.017,15971449000,2359061,2359061,256,60944,...,624445500,16.4,89502,1498,20080409,1,2008-04-09,1,1,2
14,16,미인도,2008-11-13,15652272500,0.016,15652272500,2341521,2341521,450,69444,...,641160000,31.1,103818,2446,20081113,0,2008-11-13,3,1,0
15,17,이글 아이,2008-10-09,14869812500,0.015,14869812500,2292172,2292172,407,59132,...,524374000,40.2,86957,1815,20081009,1,2008-10-09,3,1,1
16,18,007 퀀텀 오브 솔러스,2008-11-05,14389307000,0.015,14389307000,2205159,2205159,520,70774,...,630792500,51.5,100124,2734,20081105,1,2008-11-05,3,1,1
17,19,눈에는 눈 이에는 이,2008-07-31,13410811500,0.014,13410811500,2058616,2058616,445,46474,...,7025000,0.4,1662,8,20080715,0,2008-07-31,2,0,0
18,20,아내가 결혼했다,2008-10-23,12062180000,0.013,12062180000,1799447,1799447,417,57496,...,594061000,39.6,96014,2066,20081023,0,2008-10-23,3,1,0
19,21,님은 먼 곳에,2008-07-24,11205439000,0.012,11205439000,1706037,1706037,499,36555,...,32486000,2.0,4810,19,20080714,1,2008-07-24,2,0,0
20,22,점퍼,2008-02-14,10943088000,0.011,10943088000,1665268,1665268,350,43335,...,14574000,1.3,2082,6,20080212,1,2008-02-14,4,0,1
21,23,고死 : 피의 중간고사,2008-08-07,10300791000,0.011,10300791000,1634192,1634192,270,42719,...,46874000,1.0,11574,58,20080731,0,2008-08-07,2,0,0
22,24,무방비도시,2008-01-10,10591149500,0.011,10591149500,1600856,1600856,336,38306,...,526116500,24.4,81244,1774,20080110,0,2008-01-10,4,0,0
23,25,적벽대전:거대한 전쟁의 시작,2008-07-10,10192112500,0.011,10192112500,1570703,1570703,447,32719,...,7450000,0.3,1490,7,20080703,1,2008-07-10,2,0,2
24,26,원스어폰어타임,2008-01-31,10136738500,0.011,10136738500,1544486,1544486,314,37679,...,52008000,2.9,12400,63,20080124,0,2008-01-31,4,0,0
25,27,더 게임,2008-01-30,9807963501,0.010,9807963501,1479859,1479859,338,31877,...,459184501,23.3,72292,1590,20080131,0,2008-01-30,4,0,0
26,29,월ㆍE,2008-08-06,8289679500,0.009,8289679500,1325834,1325834,347,32819,...,20831500,0.6,3095,52,20080805,1,2008-08-06,2,0,1
27,30,영화는 영화다,2008-09-11,8967253000,0.009,8967253000,1311071,1311071,315,37337,...,111830000,10.4,16579,746,20080910,0,2008-09-11,3,0,0
28,31,지구가 멈추는 날,2008-12-24,8582183500,0.009,8582183500,1307068,1307068,469,22590,...,434792000,22.5,67707,2485,20081223,1,2008-12-24,4,0,1
29,32,트와일라잇,2008-12-10,8369922000,0.009,8369922000,1292332,1292332,345,28082,...,46292000,3.7,11573,60,20081204,1,2008-12-10,4,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,253,내게 남은 사랑을,2017-11-02,180693600,0.000,180693600,27414,27414,156,1656,...,17156000,0.8,2232,9,20171030,0,2017-11-02,3,1,0
2145,254,지니어스,2017-04-13,209700437,0.000,209700437,27224,27224,172,2310,...,21148400,1.0,2955,293,20170412,1,2017-04-13,1,1,2
2146,255,로스트 인 파리,2017-05-18,215591038,0.000,215591038,27206,27206,85,1708,...,12418600,0.3,1532,126,20170518,1,2017-05-18,1,1,2
2147,257,몬스터 섬의 비밀,2017-09-07,184568800,0.000,184568800,26739,26739,150,1736,...,46650800,0.7,6104,260,20170909,1,2017-09-07,3,0,2
2148,258,아기돼지 3형제와 매직램프,2017-03-23,208444600,0.000,208444600,26670,26670,135,1388,...,45994500,0.5,5772,184,20170324,1,2017-03-23,1,1,2
2149,259,메소드,2017-11-02,215611800,0.000,215611800,26577,26577,244,2933,...,21924900,0.8,2857,399,20171101,0,2017-11-02,3,1,0
2150,261,배저로와 친구들: 신비한 모험,2017-10-26,177884400,0.000,177884400,26185,26185,293,1758,...,48890700,0.6,6840,376,20171027,1,2017-10-26,3,1,2
2151,262,슈퍼 버드,2017-04-06,183154100,0.000,183154100,25964,25964,288,1858,...,49484100,1.1,6629,405,20170407,1,2017-04-06,1,1,2
2152,263,부니베어: 로거빅 컴백홈 프로젝트,2017-06-29,177955300,0.000,177955300,25908,25908,277,1799,...,50438200,0.9,6935,392,20170630,1,2017-06-29,2,1,2
2153,264,골드,2017-03-22,195316900,0.000,195316900,25612,25612,200,3102,...,31233800,1.5,4355,485,20170321,1,2017-03-22,1,1,1
2154,268,아우토반,2017-03-22,196841500,0.000,196841500,24983,24983,153,3489,...,26823000,1.3,3707,601,20170321,1,2017-03-22,1,1,2
2155,278,파워배틀 와치카: 와치가면의 역습,2017-06-01,166656500,0.000,166656500,23630,23630,246,1787,...,42720100,0.3,6046,193,20170605,0,2017-06-01,2,1,0
2156,281,토마스와 친구들: 수수께끼 해적선과 보물찾기,2017-06-29,155824700,0.000,155824700,23395,23395,145,1544,...,23512900,0.2,3562,159,20170707,1,2017-06-29,2,1,2
2157,282,유리정원,2017-10-25,160437700,0.000,160437700,22752,22752,332,4480,...,23059000,0.6,3933,627,20171024,0,2017-10-25,3,1,0
2158,284,송 투 송,2017-07-26,172525100,0.000,172525100,22518,22518,97,1526,...,24039800,0.3,3906,147,20170725,1,2017-07-26,2,0,1
2159,288,극장판 어드벤처 타임: 비밀의 아일랜드,2017-04-13,163679600,0.000,163679600,19986,19986,125,1009,...,42994200,0.7,5214,161,20170414,1,2017-04-13,1,1,1
2160,294,그 후,2017-07-06,142319508,0.000,142319508,18648,18648,168,2451,...,15539300,0.4,2170,279,20170705,0,2017-07-06,2,0,0
2161,295,오즈의 마법사 2,2017-05-03,143173700,0.000,143173700,18535,18535,142,908,...,54821600,0.5,7009,182,20170502,1,2017-05-03,1,1,2
2162,296,은혼,2017-12-07,148853500,0.000,148853500,18323,18323,137,2136,...,12993500,0.8,1599,6,20171205,1,2017-12-07,4,0,2
2163,297,신서유기 : 몽키킹의 부활,2017-11-02,129357400,0.000,129357400,18247,18247,212,1139,...,42463300,0.5,5737,293,20171103,1,2017-11-02,3,1,2
2164,299,배드 지니어스,2017-11-02,141276336,0.000,141276336,17941,17941,200,1983,...,8983500,0.5,1248,244,20171105,1,2017-11-02,3,1,2
2165,307,빅 배드 폭스,2017-11-30,120614100,0.000,120614100,16340,16340,219,1125,...,47454100,0.8,6085,284,20171202,1,2017-11-30,3,1,2
2166,308,링스,2017-04-06,136520300,0.000,136520300,16336,16336,123,1709,...,14705500,0.9,1880,155,20170405,1,2017-04-06,1,1,1
2167,315,콜로설,2017-04-20,114967100,0.000,114967100,14687,14687,305,2964,...,24375000,1.6,3367,625,20170419,1,2017-04-20,1,1,2
2168,319,개구리왕국 2,2017-03-23,99741700,0.000,99741700,14236,14236,171,819,...,30011900,0.4,4023,197,20170325,1,2017-03-23,1,1,2
2169,323,용순,2017-06-08,97538200,0.000,97538200,13268,13268,126,2558,...,8979500,0.3,1236,272,20170607,0,2017-06-08,2,1,0
2170,332,주키퍼스 와이프,2017-10-12,90190446,0.000,90190446,11795,11795,100,1705,...,5032000,0.3,705,164,20171015,1,2017-10-12,3,1,1
2171,363,나의 엔젤,2017-10-12,68315000,0.000,68315000,9097,9097,91,1433,...,6498500,0.3,957,162,20171011,1,2017-10-12,3,1,2
2172,400,베를린 신드롬,2017-07-06,54659800,0.000,54659800,7011,7011,78,844,...,7179000,0.2,998,146,20170705,1,2017-07-06,2,0,2
2173,410,암살교실: 졸업편,2017-04-21,34784500,0.000,34784500,6491,6491,46,245,...,13390000,0.4,2678,7,20170530,1,2017-04-21,1,1,2

In [20]:
df_a.Rate.describe()

count         2146
unique          14
top       15세이상관람가
freq           737
Name: Rate, dtype: object

In [21]:
Rate_var = []

for idx, a in enumerate(df_a['Rate']):
    if type(a) is not str:
        continue
    elif a == '12세이상관람가':
         Rate_var.append(0)
    elif a == '15세이상관람가':
         Rate_var.append(1)
    elif a == '청소년관람불가':
         Rate_var.append(2)
    else:
         Rate_var.append(3)
df_a['Rate_att'] = pd.Series(Rate_var)
df_a

,rank_x,movieNm,openDt,sales,salesShare_x,salesAmt_x,audiCnt_x,audiCntAnt,scrnCnt_x,showCnt_x,...,salesShare_y,audiCnt_y,showCnt_y,searchDay,Nation_y,openDt_y,openDt_season,openDt_peak,Nation_att,Rate_att
0,2,추격자,2008-02-14,33986959000,0.035,33986959000,5046096,5046096,433,106805,...,26.3,113673,2032,20080214,0,2008-02-14,4,0,0,2.0
1,3,쿵푸 팬더,2008-06-05,29996476000,0.031,29996476000,4653929,4653929,563,79850,...,30.3,105337,2790,20080605,1,2008-06-05,2,1,1,3.0
2,4,맘마미아!,2008-09-03,29571255750,0.031,29571255750,4552475,4552475,451,111024,...,4.0,11574,58,20080828,1,2008-09-03,3,0,1,0.0
3,5,과속스캔들,2008-12-03,28506879500,0.030,28506879500,4361509,4361509,408,62296,...,1.6,4731,25,20081124,0,2008-12-03,4,0,0,0.0
4,6,강철중: 공공의 적 1-1,2008-06-19,28638460100,0.030,28638460100,4313101,4313101,707,74157,...,24.1,55080,852,20080618,0,2008-06-19,2,1,0,1.0
5,7,아이언맨,2008-04-30,27798047000,0.029,27798047000,4290816,4290816,592,77942,...,46.7,152797,2823,20080430,1,2008-04-30,1,1,1,0.0
6,8,인디아나 존스 4 : 크리스탈 해골의 왕국,2008-05-22,26689440000,0.028,26689440000,4111753,4111753,771,75393,...,1.1,1254,6,20080520,1,2008-05-22,1,1,1,0.0
7,9,미이라 3:황제의 무덤,2008-07-30,26217311000,0.027,26217311000,4090885,4090885,634,64779,...,47.0,297855,3168,20080730,1,2008-07-30,2,0,1,0.0
8,10,다크 나이트,2008-08-06,26878184500,0.028,26878184500,4060490,4060490,462,63561,...,12.0,59957,795,20080805,1,2008-08-06,2,0,1,1.0
9,11,우리 생애 최고의 순간,2008-01-10,26113394000,0.027,26119898000,4018059,4018872,418,70721,...,30.8,108071,2042,20080110,0,2008-01-10,4,0,0,3.0
10,12,신기전,2008-09-04,24326353000,0.025,24326353000,3728430,3728430,585,78462,...,0.4,1976,9,20080807,0,2008-09-04,3,0,0,1.0
11,13,원티드,2008-06-26,19249245000,0.020,19249245000,2858720,2858720,512,55001,...,1.3,3680,20,20080624,1,2008-06-26,2,1,1,2.0
12,14,핸콕,2008-07-02,17844690500,0.019,17844690500,2722574,2722574,602,60236,...,44.7,167724,3404,20080702,1,2008-07-02,2,0,1,0.0
13,15,테이큰,2008-04-09,15971449000,0.017,15971449000,2359061,2359061,256,60944,...,16.4,89502,1498,20080409,1,2008-04-09,1,1,2,2.0
14,16,미인도,2008-11-13,15652272500,0.016,15652272500,2341521,2341521,450,69444,...,31.1,103818,2446,20081113,0,2008-11-13,3,1,0,2.0
15,17,이글 아이,2008-10-09,14869812500,0.015,14869812500,2292172,2292172,407,59132,...,40.2,86957,1815,20081009,1,2008-10-09,3,1,1,0.0
16,18,007 퀀텀 오브 솔러스,2008-11-05,14389307000,0.015,14389307000,2205159,2205159,520,70774,...,51.5,100124,2734,20081105,1,2008-11-05,3,1,1,1.0
17,19,눈에는 눈 이에는 이,2008-07-31,13410811500,0.014,13410811500,2058616,2058616,445,46474,...,0.4,1662,8,20080715,0,2008-07-31,2,0,0,1.0
18,20,아내가 결혼했다,2008-10-23,12062180000,0.013,12062180000,1799447,1799447,417,57496,...,39.6,96014,2066,20081023,0,2008-10-23,3,1,0,2.0
19,21,님은 먼 곳에,2008-07-24,11205439000,0.012,11205439000,1706037,1706037,499,36555,...,2.0,4810,19,20080714,1,2008-07-24,2,0,0,1.0
20,22,점퍼,2008-02-14,10943088000,0.011,10943088000,1665268,1665268,350,43335,...,1.3,2082,6,20080212,1,2008-02-14,4,0,1,1.0
21,23,고死 : 피의 중간고사,2008-08-07,10300791000,0.011,10300791000,1634192,1634192,270,42719,...,1.0,11574,58,20080731,0,2008-08-07,2,0,0,1.0
22,24,무방비도시,2008-01-10,10591149500,0.011,10591149500,1600856,1600856,336,38306,...,24.4,81244,1774,20080110,0,2008-01-10,4,0,0,1.0
23,25,적벽대전:거대한 전쟁의 시작,2008-07-10,10192112500,0.011,10192112500,1570703,1570703,447,32719,...,0.3,1490,7,20080703,1,2008-07-10,2,0,2,1.0
24,26,원스어폰어타임,2008-01-31,10136738500,0.011,10136738500,1544486,1544486,314,37679,...,2.9,12400,63,20080124,0,2008-01-31,4,0,0,0.0
25,27,더 게임,2008-01-30,9807963501,0.010,9807963501,1479859,1479859,338,31877,...,23.3,72292,1590,20080131,0,2008-01-30,4,0,0,1.0
26,29,월ㆍE,2008-08-06,8289679500,0.009,8289679500,1325834,1325834,347,32819,...,0.6,3095,52,20080805,1,2008-08-06,2,0,1,3.0
27,30,영화는 영화다,2008-09-11,8967253000,0.009,8967253000,1311071,1311071,315,37337,...,10.4,16579,746,20080910,0,2008-09-11,3,0,0,2.0
28,31,지구가 멈추는 날,2008-12-24,8582183500,0.009,8582183500,1307068,1307068,469,22590,...,22.5,67707,2485,20081223,1,2008-12-24,4,0,1,0.0
29,32,트와일라잇,2008-12-10,8369922000,0.009,8369922000,1292332,1292332,345,28082,...,3.7,11573,60,20081204,1,2008-12-10,4,0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,253,내게 남은 사랑을,2017-11-02,180693600,0.000,180693600,27414,27414,156,1656,...,0.8,2232,9,20171030,0,2017-11-02,3,1,0,2.0
2145,254,지니어스,2017-04-13,209700437,0.000,209700437,27224,27224,172,2310,...,1.0,2955,293,20170412,1,2017-04-13,1,1,2,0.0
2146,255,로스트 인 파리,2017-05-18,215591038,0.000,215591038,27206,27206,85,1708,...,0.3,1532,126,20170518,1,2017-05-18,1,1,2,NaN
2147,257,몬스터 섬의 비밀,2017-09-07,184568800,0.000,184568800,26739,26739,150,1736,...,0.7,6104,260,20170909,1,2017-09-07,3,0,2,NaN
2148,258,아기돼지 3형제와 매직램프,2017-03-23,208444600,0.000,208444600,26670,26670,135,1388,...,0.5,5772,184,20170324,1,2017-03-23,1,1,2,NaN
2149,259,메소드,2017-11-02,215611800,0.000,215611800,26577,26577,244,2933,...,0.8,2857,399,20171101,0,2017-11-02,3,1,0,NaN
2150,261,배저로와 친구들: 신비한 모험,2017-10-26,177884400,0.000,177884400,26185,26185,293,1758,...,0.6,6840,376,20171027,1,2017-10-26,3,1,2,NaN
2151,262,슈퍼 버드,2017-04-06,183154100,0.000,183154100,25964,25964,288,1858,...,1.1,6629,405,20170407,1,2017-04-06,1,1,2,NaN
2152,263,부니베어: 로거빅 컴백홈 프로젝트,2017-06-29,177955300,0.000,177955300,25908,25908,277,1799,...,0.9,6935,392,20170630,1,2017-06-29,2,1,2,NaN
2153,264,골드,2017-03-22,195316900,0.000,195316900,25612,25612,200,3102,...,1.5,4355,485,20170321,1,2017-03-22,1,1,1,NaN
2154,268,아우토반,2017-03-22,196841500,0.000,196841500,24983,24983,153,3489,...,1.3,3707,601,20170321,1,2017-03-22,1,1,2,NaN
2155,278,파워배틀 와치카: 와치가면의 역습,2017-06-01,166656500,0.000,166656500,23630,23630,246,1787,...,0.3,6046,193,20170605,0,2017-06-01,2,1,0,NaN
2156,281,토마스와 친구들: 수수께끼 해적선과 보물찾기,2017-06-29,155824700,0.000,155824700,23395,23395,145,1544,...,0.2,3562,159,20170707,1,2017-06-29,2,1,2,NaN
2157,282,유리정원,2017-10-25,160437700,0.000,160437700,22752,22752,332,4480,...,0.6,3933,627,20171024,0,2017-10-25,3,1,0,NaN
2158,284,송 투 송,2017-07-26,172525100,0.000,172525100,22518,22518,97,1526,...,0.3,3906,147,20170725,1,2017-07-26,2,0,1,NaN
2159,288,극장판 어드벤처 타임: 비밀의 아일랜드,2017-04-13,163679600,0.000,163679600,19986,19986,125,1009,...,0.7,5214,161,20170414,1,2017-04-13,1,1,1,NaN
2160,294,그 후,2017-07-06,142319508,0.000,142319508,18648,18648,168,2451,...,0.4,2170,279,20170705,0,2017-07-06,2,0,0,NaN
2161,295,오즈의 마법사 2,2017-05-03,143173700,0.000,143173700,18535,18535,142,908,...,0.5,7009,182,20170502,1,2017-05-03,1,1,2,NaN
2162,296,은혼,2017-12-07,148853500,0.000,148853500,18323,18323,137,2136,...,0.8,1599,6,20171205,1,2017-12-07,4,0,2,NaN
2163,297,신서유기 : 몽키킹의 부활,2017-11-02,129357400,0.000,129357400,18247,18247,212,1139,...,0.5,5737,293,20171103,1,2017-11-02,3,1,2,NaN
2164,299,배드 지니어스,2017-11-02,141276336,0.000,141276336,17941,17941,200,1983,...,0.5,1248,244,20171105,1,2017-11-02,3,1,2,NaN
2165,307,빅 배드 폭스,2017-11-30,120614100,0.000,120614100,16340,16340,219,1125,...,0.8,6085,284,20171202,1,2017-11-30,3,1,2,NaN
2166,308,링스,2017-04-06,136520300,0.000,136520300,16336,16336,123,1709,...,0.9,1880,155,20170405,1,2017-04-06,1,1,1,NaN
2167,315,콜로설,2017-04-20,114967100,0.000,114967100,14687,14687,305,2964,...,1.6,3367,625,20170419,1,2017-04-20,1,1,2,NaN
2168,319,개구리왕국 2,2017-03-23,99741700,0.000,99741700,14236,14236,171,819,...,0.4,4023,197,20170325,1,2017-03-23,1,1,2,NaN
2169,323,용순,2017-06-08,97538200,0.000,97538200,13268,13268,126,2558,...,0.3,1236,272,20170607,0,2017-06-08,2,1,0,NaN
2170,332,주키퍼스 와이프,2017-10-12,90190446,0.000,90190446,11795,11795,100,1705,...,0.3,705,164,20171015,1,2017-10-12,3,1,1,NaN
2171,363,나의 엔젤,2017-10-12,68315000,0.000,68315000,9097,9097,91,1433,...,0.3,957,162,20171011,1,2017-10-12,3,1,2,NaN
2172,400,베를린 신드롬,2017-07-06,54659800,0.000,54659800,7011,7011,78,844,...,0.2,998,146,20170705,1,2017-07-06,2,0,2,NaN
2173,410,암살교실: 졸업편,2017-04-21,34784500,0.000,34784500,6491,6491,46,245,...,0.4,2678,7,20170530,1,2017-04-21,1,1,2,NaN

In [22]:
df_a.Rate_att.describe()

count    2146.000000
mean        1.427307
std         1.078106
min         0.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         3.000000
Name: Rate_att, dtype: float64