In [1]:
import pandas as pd
from pandas import DataFrame, Series
import os
import sys
# import service_identity
import numpy as np
import datetime

In [2]:
movie_2017 = pd.read_excel('./boxoffice_list/2017_boxoffice.xlsx')

In [3]:
movie_2017

,연도별 박스오피스 검색 리스트,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,순위,영화명,개봉일,매출액,매출액 점유율,관객수,스크린수,상영횟수,대표국적,국적,배급사
2,1,택시운전사,2017-08-02 00:00:00,95853645649,0.055,12186327,1906,184075,한국,한국,(주)쇼박스
3,2,신과함께-죄와 벌,2017-12-20 00:00:00,68350496432,0.039,8539495,1912,91301,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
4,3,공조,2017-01-18 00:00:00,63783051326,0.036,7817618,1392,142989,한국,한국,씨제이이앤엠(주)
5,4,스파이더맨: 홈 커밍,2017-07-05 00:00:00,59125813820,0.034,7258678,1965,164448,미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점
6,5,범죄도시,2017-10-03 00:00:00,56318014149,0.032,6879841,1315,149334,한국,한국,"메가박스중앙(주)플러스엠,(주)키위미디어그룹"
7,6,군함도,2017-07-26 00:00:00,50510565168,0.029,6592151,2027,108775,한국,한국,씨제이이앤엠(주)
8,7,청년경찰,2017-08-09 00:00:00,44381150516,0.025,5653270,1102,118544,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
9,8,더 킹,2017-01-18 00:00:00,43488814535,0.025,5317693,1310,107983,한국,한국,(주)넥스트엔터테인먼트월드(NEW)
10,9,미녀와 야수,2017-03-16 00:00:00,42133751579,0.024,5138328,1627,140561,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
11,10,킹스맨: 골든 서클,2017-09-27 00:00:00,40987484736,0.023,4945484,1687,95922,미국,"미국,영국",이십세기폭스코리아(주)
12,11,토르: 라그나로크,2017-10-25 00:00:00,39227691395,0.022,4853778,1640,137423,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
13,12,꾼,2017-11-22 00:00:00,31312029795,0.018,4018035,1314,117398,한국,한국,(주)쇼박스
14,13,강철비,2017-12-14 00:00:00,31994897566,0.018,4014293,1426,66760,한국,한국,(주)넥스트엔터테인먼트월드(NEW)
15,14,남한산성,2017-10-03 00:00:00,31225083792,0.018,3849087,1229,71101,한국,한국,씨제이이앤엠(주)
16,15,미이라,2017-06-06 00:00:00,30504689978,0.017,3689325,1257,105228,미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
17,16,분노의 질주: 더 익스트림,2017-04-12 00:00:00,29981156348,0.017,3653238,1469,113241,미국,"미국,일본,프랑스,캐나다",유니버설픽쳐스인터내셔널 코리아(유)
18,17,너의 이름은.,2017-01-04 00:00:00,29251793156,0.017,3637608,947,82978,일본,일본,메가박스중앙(주)플러스엠
19,18,슈퍼배드 3,2017-07-26 00:00:00,24217091019,0.014,3324874,1057,59388,미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
20,19,아이 캔 스피크,2017-09-21 00:00:00,25526451186,0.015,3279296,1140,93012,한국,한국,"롯데쇼핑㈜롯데엔터테인먼트,(주)리틀빅픽쳐스"
21,20,캐리비안의 해적: 죽은 자는 말이 없다,2017-05-24 00:00:00,24975495122,0.014,3049894,1357,85225,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
22,21,프리즌,2017-03-23 00:00:00,23790276987,0.014,2931897,1047,89024,한국,한국,(주)쇼박스
23,22,덩케르크,2017-07-20 00:00:00,24550541348,0.014,2788732,1252,65906,미국,"미국,영국",워너브러더스 코리아(주)
24,23,가디언즈 오브 갤럭시 VOL. 2,2017-05-03 00:00:00,23452686686,0.013,2735721,1218,63789,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
25,24,살인자의 기억법,2017-09-06 00:00:00,21375287492,0.012,2658589,1064,88686,한국,한국,(주)쇼박스
26,25,트랜스포머: 최후의 기사,2017-06-21 00:00:00,21501959228,0.012,2614601,1739,87234,미국,미국,롯데쇼핑㈜롯데엔터테인먼트
27,26,보안관,2017-05-03 00:00:00,20844488409,0.012,2588628,1091,63709,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
28,27,조작된 도시,2017-02-09 00:00:00,20143992587,0.011,2515501,1019,62241,한국,한국,씨제이이앤엠(주)
29,28,보스 베이비,2017-05-03 00:00:00,18936306704,0.011,2452245,1116,48379,미국,미국,씨제이이앤엠(주)
...,...,...,...,...,...,...,...,...,...,...,...
4779,4652,커커시리: 마운틴 패트롤,NaN,0,0,0,1,2,중국,"중국,홍콩",NaN
4780,4652,내 친구의 집은 어디인가,1996-08-17 00:00:00,0,0,0,1,2,이란,이란,NaN
4781,4652,노스 컨츄리,2006-04-27 00:00:00,0,0,0,1,1,미국,미국,워너브러더스 코리아(주)
4782,4652,가족의 탄생,2006-05-18 00:00:00,0,0,0,1,2,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
4783,4652,천리주단기,2006-07-20 00:00:00,0,0,0,1,2,중국,"중국,일본",소니픽쳐스릴리징코리아
4784,4652,밀양,2007-05-23 00:00:00,0,0,0,1,1,한국,한국,(주)시네마서비스
4785,4652,잔느 딜망,2008-05-09 00:00:00,0,0,0,1,1,프랑스,프랑스,NaN
4786,4652,깊고 푸른 밤,1985-03-01 00:00:00,0,0,0,1,2,한국,한국,NaN
4787,4652,혈맥,NaN,0,0,0,1,2,한국,한국,NaN
4788,4652,개그맨,1989-06-24 00:00:00,0,0,0,1,5,한국,한국,NaN
4789,4652,매란방,2009-04-16 00:00:00,0,0,0,1,2,중국,중국,에스케이텔레콤(주)
4790,4652,시,2010-05-13 00:00:00,0,0,0,1,1,한국,한국,(주)넥스트엔터테인먼트월드(NEW)
4791,4652,참새들의 합창,2010-05-05 00:00:00,0,0,0,1,1,이란,이란,(주)유니코리아문예투자
4792,4652,바보들의 행진,1975-05-31 00:00:00,0,0,0,1,2,한국,한국,NaN
4793,4652,페데리코 펠리니 회고전,NaN,0,0,0,1,3,이탈리아,이탈리아,NaN
4794,4652,삼포가는 길,1975-05-23 00:00:00,0,0,0,1,2,한국,한국,NaN
4795,4652,미국의 바람과 불,2012-07-26 00:00:00,0,0,0,1,2,한국,한국,(주)시네마달
4796,4652,샤오린 : 최후의 결전,2011-08-25 00:00:00,0,0,0,1,2,홍콩,"홍콩,중국",(주)에스비에스콘텐츠허브
4797,4652,아프리카 - 물의 전쟁,NaN,0,0,0,1,1,한국,한국,NaN
4798,4652,씨민과 나데르의 별거,2011-10-13 00:00:00,0,0,0,1,2,이란,이란,(주)영화사 진진
4799,4652,사랑을 카피하다,2011-05-05 00:00:00,0,0,0,1,2,프랑스,프랑스,주식회사 마운틴픽쳐스
4800,4652,심플 라이프,2012-11-22 00:00:00,0,0,0,1,2,홍콩,홍콩,(주)미로비젼
4801,4652,훌리오와 에밀리아,2012-08-30 00:00:00,0,0,0,1,2,칠레,"칠레,아르헨티나,포르투갈,프랑스",찬란
4802,4652,라폴로니드 : 관용의집,2012-09-20 00:00:00,0,0,0,1,2,프랑스,프랑스,(주)액티버스엔터테인먼트
4803,4652,개를 훔치는 완벽한 방법,2014-12-31 00:00:00,0,0,0,1,2,한국,한국,"(주)리틀빅픽쳐스,(주)대명문화공장"
4804,4652,하늘의 황금마차,2014-09-04 00:00:00,0,0,0,1,1,한국,한국,(주)영화사 진진
4805,4652,까미유 끌로델,2013-10-24 00:00:00,0,0,0,1,2,프랑스,프랑스,찬란
4806,4652,망원동 인공위성,2015-02-05 00:00:00,0,0,0,1,1,한국,한국,(주)시네마달
4807,4652,마이 플레이스,2014-01-30 00:00:00,0,0,0,1,1,한국,한국,KT&G 상상마당 영화사업팀 컴퍼니에스에스(주)
4808,합계,NaN,NaN,1756577851113,NaN,219876227,165937,6261651,NaN,NaN,NaN

In [5]:
movie_2017.rename(columns={'Unnamed: 1':'영화명','Unnamed: 2':'개봉일'}, inplace=True)

In [6]:
a = movie_2017.drop(1,0)

In [7]:
b = a.drop(0)

In [8]:
b

,연도별 박스오피스 검색 리스트,영화명,개봉일,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
2,1,택시운전사,2017-08-02 00:00:00,95853645649,0.055,12186327,1906,184075,한국,한국,(주)쇼박스
3,2,신과함께-죄와 벌,2017-12-20 00:00:00,68350496432,0.039,8539495,1912,91301,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
4,3,공조,2017-01-18 00:00:00,63783051326,0.036,7817618,1392,142989,한국,한국,씨제이이앤엠(주)
5,4,스파이더맨: 홈 커밍,2017-07-05 00:00:00,59125813820,0.034,7258678,1965,164448,미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점
6,5,범죄도시,2017-10-03 00:00:00,56318014149,0.032,6879841,1315,149334,한국,한국,"메가박스중앙(주)플러스엠,(주)키위미디어그룹"
7,6,군함도,2017-07-26 00:00:00,50510565168,0.029,6592151,2027,108775,한국,한국,씨제이이앤엠(주)
8,7,청년경찰,2017-08-09 00:00:00,44381150516,0.025,5653270,1102,118544,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
9,8,더 킹,2017-01-18 00:00:00,43488814535,0.025,5317693,1310,107983,한국,한국,(주)넥스트엔터테인먼트월드(NEW)
10,9,미녀와 야수,2017-03-16 00:00:00,42133751579,0.024,5138328,1627,140561,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
11,10,킹스맨: 골든 서클,2017-09-27 00:00:00,40987484736,0.023,4945484,1687,95922,미국,"미국,영국",이십세기폭스코리아(주)
12,11,토르: 라그나로크,2017-10-25 00:00:00,39227691395,0.022,4853778,1640,137423,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
13,12,꾼,2017-11-22 00:00:00,31312029795,0.018,4018035,1314,117398,한국,한국,(주)쇼박스
14,13,강철비,2017-12-14 00:00:00,31994897566,0.018,4014293,1426,66760,한국,한국,(주)넥스트엔터테인먼트월드(NEW)
15,14,남한산성,2017-10-03 00:00:00,31225083792,0.018,3849087,1229,71101,한국,한국,씨제이이앤엠(주)
16,15,미이라,2017-06-06 00:00:00,30504689978,0.017,3689325,1257,105228,미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
17,16,분노의 질주: 더 익스트림,2017-04-12 00:00:00,29981156348,0.017,3653238,1469,113241,미국,"미국,일본,프랑스,캐나다",유니버설픽쳐스인터내셔널 코리아(유)
18,17,너의 이름은.,2017-01-04 00:00:00,29251793156,0.017,3637608,947,82978,일본,일본,메가박스중앙(주)플러스엠
19,18,슈퍼배드 3,2017-07-26 00:00:00,24217091019,0.014,3324874,1057,59388,미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
20,19,아이 캔 스피크,2017-09-21 00:00:00,25526451186,0.015,3279296,1140,93012,한국,한국,"롯데쇼핑㈜롯데엔터테인먼트,(주)리틀빅픽쳐스"
21,20,캐리비안의 해적: 죽은 자는 말이 없다,2017-05-24 00:00:00,24975495122,0.014,3049894,1357,85225,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
22,21,프리즌,2017-03-23 00:00:00,23790276987,0.014,2931897,1047,89024,한국,한국,(주)쇼박스
23,22,덩케르크,2017-07-20 00:00:00,24550541348,0.014,2788732,1252,65906,미국,"미국,영국",워너브러더스 코리아(주)
24,23,가디언즈 오브 갤럭시 VOL. 2,2017-05-03 00:00:00,23452686686,0.013,2735721,1218,63789,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
25,24,살인자의 기억법,2017-09-06 00:00:00,21375287492,0.012,2658589,1064,88686,한국,한국,(주)쇼박스
26,25,트랜스포머: 최후의 기사,2017-06-21 00:00:00,21501959228,0.012,2614601,1739,87234,미국,미국,롯데쇼핑㈜롯데엔터테인먼트
27,26,보안관,2017-05-03 00:00:00,20844488409,0.012,2588628,1091,63709,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
28,27,조작된 도시,2017-02-09 00:00:00,20143992587,0.011,2515501,1019,62241,한국,한국,씨제이이앤엠(주)
29,28,보스 베이비,2017-05-03 00:00:00,18936306704,0.011,2452245,1116,48379,미국,미국,씨제이이앤엠(주)
30,29,재심,2017-02-15 00:00:00,19266319637,0.011,2421197,935,68402,한국,한국,"오퍼스픽쳐스,CGV아트하우스"
31,30,박열,2017-06-28 00:00:00,18093639795,0.01,2359206,1176,78499,한국,한국,메가박스중앙(주)플러스엠
...,...,...,...,...,...,...,...,...,...,...,...
4779,4652,커커시리: 마운틴 패트롤,NaN,0,0,0,1,2,중국,"중국,홍콩",NaN
4780,4652,내 친구의 집은 어디인가,1996-08-17 00:00:00,0,0,0,1,2,이란,이란,NaN
4781,4652,노스 컨츄리,2006-04-27 00:00:00,0,0,0,1,1,미국,미국,워너브러더스 코리아(주)
4782,4652,가족의 탄생,2006-05-18 00:00:00,0,0,0,1,2,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
4783,4652,천리주단기,2006-07-20 00:00:00,0,0,0,1,2,중국,"중국,일본",소니픽쳐스릴리징코리아
4784,4652,밀양,2007-05-23 00:00:00,0,0,0,1,1,한국,한국,(주)시네마서비스
4785,4652,잔느 딜망,2008-05-09 00:00:00,0,0,0,1,1,프랑스,프랑스,NaN
4786,4652,깊고 푸른 밤,1985-03-01 00:00:00,0,0,0,1,2,한국,한국,NaN
4787,4652,혈맥,NaN,0,0,0,1,2,한국,한국,NaN
4788,4652,개그맨,1989-06-24 00:00:00,0,0,0,1,5,한국,한국,NaN
4789,4652,매란방,2009-04-16 00:00:00,0,0,0,1,2,중국,중국,에스케이텔레콤(주)
4790,4652,시,2010-05-13 00:00:00,0,0,0,1,1,한국,한국,(주)넥스트엔터테인먼트월드(NEW)
4791,4652,참새들의 합창,2010-05-05 00:00:00,0,0,0,1,1,이란,이란,(주)유니코리아문예투자
4792,4652,바보들의 행진,1975-05-31 00:00:00,0,0,0,1,2,한국,한국,NaN
4793,4652,페데리코 펠리니 회고전,NaN,0,0,0,1,3,이탈리아,이탈리아,NaN
4794,4652,삼포가는 길,1975-05-23 00:00:00,0,0,0,1,2,한국,한국,NaN
4795,4652,미국의 바람과 불,2012-07-26 00:00:00,0,0,0,1,2,한국,한국,(주)시네마달
4796,4652,샤오린 : 최후의 결전,2011-08-25 00:00:00,0,0,0,1,2,홍콩,"홍콩,중국",(주)에스비에스콘텐츠허브
4797,4652,아프리카 - 물의 전쟁,NaN,0,0,0,1,1,한국,한국,NaN
4798,4652,씨민과 나데르의 별거,2011-10-13 00:00:00,0,0,0,1,2,이란,이란,(주)영화사 진진
4799,4652,사랑을 카피하다,2011-05-05 00:00:00,0,0,0,1,2,프랑스,프랑스,주식회사 마운틴픽쳐스
4800,4652,심플 라이프,2012-11-22 00:00:00,0,0,0,1,2,홍콩,홍콩,(주)미로비젼
4801,4652,훌리오와 에밀리아,2012-08-30 00:00:00,0,0,0,1,2,칠레,"칠레,아르헨티나,포르투갈,프랑스",찬란
4802,4652,라폴로니드 : 관용의집,2012-09-20 00:00:00,0,0,0,1,2,프랑스,프랑스,(주)액티버스엔터테인먼트
4803,4652,개를 훔치는 완벽한 방법,2014-12-31 00:00:00,0,0,0,1,2,한국,한국,"(주)리틀빅픽쳐스,(주)대명문화공장"
4804,4652,하늘의 황금마차,2014-09-04 00:00:00,0,0,0,1,1,한국,한국,(주)영화사 진진
4805,4652,까미유 끌로델,2013-10-24 00:00:00,0,0,0,1,2,프랑스,프랑스,찬란
4806,4652,망원동 인공위성,2015-02-05 00:00:00,0,0,0,1,1,한국,한국,(주)시네마달
4807,4652,마이 플레이스,2014-01-30 00:00:00,0,0,0,1,1,한국,한국,KT&G 상상마당 영화사업팀 컴퍼니에스에스(주)
4808,합계,NaN,NaN,1756577851113,NaN,219876227,165937,6261651,NaN,NaN,NaN

b.drop({'Unnamed: 3','Unnamed: 4','Unnamed: 5','Unnamed: 6','Unnamed: 7', 'Unnamed: 8','Unnamed: 9','Unnamed: 10'}, axis=1)

In [9]:
# a.month
df = pd.DataFrame({'영화명':b['영화명'], '개봉일': b['개봉일'], '개봉일 특성':''})
# for a in b['개봉일']:
#     print(a.month)
#     print(type(a.month))

#     if a.month >= 3 and a.month <= 5:
#         a.month = 1
#     elif a.month >= 6 and a.month <= 8: 
#         a.month = 2 
#     elif a.month >= 9 and a.month <= 11: 
#         a.month = 3 
#     else: 
#         a.month = 4 
# # return a.month
# # if b[]
df

                        영화명                  개봉일 개봉일 특성
2                     택시운전사  2017-08-02 00:00:00
3                 신과함께-죄와 벌  2017-12-20 00:00:00
4                        공조  2017-01-18 00:00:00
5               스파이더맨: 홈 커밍  2017-07-05 00:00:00
6                      범죄도시  2017-10-03 00:00:00
7                       군함도  2017-07-26 00:00:00
8                      청년경찰  2017-08-09 00:00:00
9                       더 킹  2017-01-18 00:00:00
10                   미녀와 야수  2017-03-16 00:00:00
11               킹스맨: 골든 서클  2017-09-27 00:00:00
12                토르: 라그나로크  2017-10-25 00:00:00
13                        꾼  2017-11-22 00:00:00
14                      강철비  2017-12-14 00:00:00
15                     남한산성  2017-10-03 00:00:00
16                      미이라  2017-06-06 00:00:00
17           분노의 질주: 더 익스트림  2017-04-12 00:00:00
18                  너의 이름은.  2017-01-04 00:00:00
19                   슈퍼배드 3  2017-07-26 00:00:00
20                 아이 캔 스피크  2017-09-21 00:00:00
21    캐리비안의 해적: 죽은 자는 말이 없다  2017-05-24 00:00:00
22                      프리즌  2017-03-23 00:00:00
23                     덩케르크  2017-07-20 00:00:00
24       가디언즈 오브 갤럭시 VOL. 2  2017-05-03 00:00:00
25                 살인자의 기억법  2017-09-06 00:00:00
26            트랜스포머: 최후의 기사  2017-06-21 00:00:00
27                      보안관  2017-05-03 00:00:00
28                   조작된 도시  2017-02-09 00:00:00
29                   보스 베이비  2017-05-03 00:00:00
30                       재심  2017-02-15 00:00:00
31                       박열  2017-06-28 00:00:00
...                     ...                  ...    ...
4779          커커시리: 마운틴 패트롤                  NaN
4780          내 친구의 집은 어디인가  1996-08-17 00:00:00
4781                 노스 컨츄리  2006-04-27 00:00:00
4782                 가족의 탄생  2006-05-18 00:00:00
4783                  천리주단기  2006-07-20 00:00:00
4784                     밀양  2007-05-23 00:00:00
4785                  잔느 딜망  2008-05-09 00:00:00
4786                깊고 푸른 밤  1985-03-01 00:00:00
4787                     혈맥                  NaN
4788                    개그맨  1989-06-24 00:00:00
4789                    매란방  2009-04-16 00:00:00
4790                      시  2010-05-13 00:00:00
4791                참새들의 합창  2010-05-05 00:00:00
4792                바보들의 행진  1975-05-31 00:00:00
4793           페데리코 펠리니 회고전                  NaN
4794                 삼포가는 길  1975-05-23 00:00:00
4795              미국의 바람과 불  2012-07-26 00:00:00
4796           샤오린 : 최후의 결전  2011-08-25 00:00:00
4797           아프리카 - 물의 전쟁                  NaN
4798            씨민과 나데르의 별거  2011-10-13 00:00:00
4799               사랑을 카피하다  2011-05-05 00:00:00
4800                 심플 라이프  2012-11-22 00:00:00
4801              훌리오와 에밀리아  2012-08-30 00:00:00
4802           라폴로니드 : 관용의집  2012-09-20 00:00:00
4803          개를 훔치는 완벽한 방법  2014-12-31 00:00:00
4804               하늘의 황금마차  2014-09-04 00:00:00
4805                까미유 끌로델  2013-10-24 00:00:00
4806               망원동 인공위성  2015-02-05 00:00:00
4807                마이 플레이스  2014-01-30 00:00:00
4808                    NaN                  NaN

[4807 rows x 3 columns]

In [10]:
for idx, a in enumerate(df['개봉일']):
    if type(a) is not datetime.datetime:
        continue
    if a.month >= 3 and a.month <= 5: 
        df.iloc[idx]['개봉일 특성'] = 1
    elif a.month >= 6 and a.month <= 8: 
        df.iloc[idx]['개봉일 특성'] = 2
    elif a.month >= 9 and a.month <= 11: 
        df.iloc[idx]['개봉일 특성'] = 3
    else: 
        df.iloc[idx]['개봉일 특성'] = 4
df

                        영화명                  개봉일 개봉일 특성
2                     택시운전사  2017-08-02 00:00:00      2
3                 신과함께-죄와 벌  2017-12-20 00:00:00      4
4                        공조  2017-01-18 00:00:00      4
5               스파이더맨: 홈 커밍  2017-07-05 00:00:00      2
6                      범죄도시  2017-10-03 00:00:00      3
7                       군함도  2017-07-26 00:00:00      2
8                      청년경찰  2017-08-09 00:00:00      2
9                       더 킹  2017-01-18 00:00:00      4
10                   미녀와 야수  2017-03-16 00:00:00      1
11               킹스맨: 골든 서클  2017-09-27 00:00:00      3
12                토르: 라그나로크  2017-10-25 00:00:00      3
13                        꾼  2017-11-22 00:00:00      3
14                      강철비  2017-12-14 00:00:00      4
15                     남한산성  2017-10-03 00:00:00      3
16                      미이라  2017-06-06 00:00:00      2
17           분노의 질주: 더 익스트림  2017-04-12 00:00:00      1
18                  너의 이름은.  2017-01-04 00:00:00      4
19                   슈퍼배드 3  2017-07-26 00:00:00      2
20                 아이 캔 스피크  2017-09-21 00:00:00      3
21    캐리비안의 해적: 죽은 자는 말이 없다  2017-05-24 00:00:00      1
22                      프리즌  2017-03-23 00:00:00      1
23                     덩케르크  2017-07-20 00:00:00      2
24       가디언즈 오브 갤럭시 VOL. 2  2017-05-03 00:00:00      1
25                 살인자의 기억법  2017-09-06 00:00:00      3
26            트랜스포머: 최후의 기사  2017-06-21 00:00:00      2
27                      보안관  2017-05-03 00:00:00      1
28                   조작된 도시  2017-02-09 00:00:00      4
29                   보스 베이비  2017-05-03 00:00:00      1
30                       재심  2017-02-15 00:00:00      4
31                       박열  2017-06-28 00:00:00      2
...                     ...                  ...    ...
4779          커커시리: 마운틴 패트롤                  NaN
4780          내 친구의 집은 어디인가  1996-08-17 00:00:00      2
4781                 노스 컨츄리  2006-04-27 00:00:00      1
4782                 가족의 탄생  2006-05-18 00:00:00      1
4783                  천리주단기  2006-07-20 00:00:00      2
4784                     밀양  2007-05-23 00:00:00      1
4785                  잔느 딜망  2008-05-09 00:00:00      1
4786                깊고 푸른 밤  1985-03-01 00:00:00      1
4787                     혈맥                  NaN
4788                    개그맨  1989-06-24 00:00:00      2
4789                    매란방  2009-04-16 00:00:00      1
4790                      시  2010-05-13 00:00:00      1
4791                참새들의 합창  2010-05-05 00:00:00      1
4792                바보들의 행진  1975-05-31 00:00:00      1
4793           페데리코 펠리니 회고전                  NaN
4794                 삼포가는 길  1975-05-23 00:00:00      1
4795              미국의 바람과 불  2012-07-26 00:00:00      2
4796           샤오린 : 최후의 결전  2011-08-25 00:00:00      2
4797           아프리카 - 물의 전쟁                  NaN
4798            씨민과 나데르의 별거  2011-10-13 00:00:00      3
4799               사랑을 카피하다  2011-05-05 00:00:00      1
4800                 심플 라이프  2012-11-22 00:00:00      3
4801              훌리오와 에밀리아  2012-08-30 00:00:00      2
4802           라폴로니드 : 관용의집  2012-09-20 00:00:00      3
4803          개를 훔치는 완벽한 방법  2014-12-31 00:00:00      4
4804               하늘의 황금마차  2014-09-04 00:00:00      3
4805                까미유 끌로델  2013-10-24 00:00:00      3
4806               망원동 인공위성  2015-02-05 00:00:00      4
4807                마이 플레이스  2014-01-30 00:00:00      4
4808                    NaN                  NaN

[4807 rows x 3 columns]

In [11]:
df.to_csv('개봉일.csv', index=False)