### 영화 일별 박스오피스 추출하는 법

In [11]:
import pandas as pd
import datetime
import requests

In [12]:
key1 = 'ca3f4432da66e0556de8179d18762a19'
key2 = 'a37309d4545a0c715c2171adbda24a74'
# # url = 'http://www.kobis.or.kr'
# MovieUrl = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=ca3f4432da66e0556de8179d18762a19&openStartDt=2016%itemPerPage =100'
# MoviePage =  requests(MovieUrl)
# # para = MOOVIE_INFO_URL
# # encText = urllib.parse.quote("")

In [13]:
def Data_Crawling(start_date, end_date, keys = key1 ):
    final_list = []
    url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json'
    
    for single_date in pd.date_range(start_date, end_date ):
        for multi, rep in zip(['Y', 'Y', 'N', 'N'], ['K','F', 'K', 'F']) :
            payload = {
                'key' : keys,
                'targetDt' : single_date.strftime('%Y%m%d'),
                'itemPerPage' : '100',
                'multiMovieYn' : multi,
                'repNationCd' : rep
            }
            req = requests.get(url, params = payload)
            
            for item in req.json()['boxOfficeResult']['dailyBoxOfficeList']:
                temp_list = []
                key_list = []
                for key, value in item.items():
                    key_list.append(key)
                    temp_list.append(value)
                    
                temp_list.append(single_date)
                key_list.append('CurrentDate')
                
                temp_list.append(multi)
                key_list.append('multi')
                
                temp_list.append(rep)
                key_list.append('Nation')
                
                final_list.append(temp_list)
                
        return pd.DataFrame(final_list, columns = key_list)
    
movie = Data_Crawling('20170101', '20171231', keys = key1)
movie.to_csv('2017movie.csv', index = False)

In [14]:
movie = pd.read_csv('2017movie.csv')

In [15]:
movie

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,...,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,CurrentDate,multi,Nation
0,1,1,0,OLD,20161701,위켄즈,2016-12-22,765700,30.0,-964300,...,17988700,93,-101,-52.1,2354,10,11,2017-01-01,Y,K
1,2,2,4,OLD,20161603,순종,2016-11-17,447000,17.5,241000,...,385404200,73,48,192.0,54529,2,2,2017-01-01,Y,K
2,3,3,-1,OLD,20162545,"무현, 두 도시 이야기",2016-10-26,410000,16.1,-309600,...,1511840600,60,-35,-36.8,192728,5,6,2017-01-01,Y,K
3,4,4,-1,OLD,20159286,연애담,2016-11-17,315000,12.4,-149000,...,183011100,38,-26,-40.6,22418,3,3,2017-01-01,Y,K
4,5,5,-1,OLD,20164527,부릉! 부릉! 브루미즈: 스피더의 모험 일기,2016-12-15,186000,7.3,-76500,...,81314500,21,-12,-36.4,10229,3,3,2017-01-01,Y,K
5,6,6,2,OLD,20153401,파파좀비,2016-12-29,109000,4.3,-28500,...,1704500,18,0,0.0,274,4,4,2017-01-01,Y,K
6,7,7,0,OLD,20162608,나의 살던 고향은,2016-11-24,84000,3.3,-67000,...,81080600,12,-8,-40.0,10698,2,2,2017-01-01,Y,K
7,8,8,7,OLD,20163011,우리 손자 베스트,2016-12-08,73000,2.9,53000,...,11442500,11,7,175.0,1957,2,2,2017-01-01,Y,K
8,9,9,0,NEW,20169730,당신자신과 당신의 것,2016-11-10,89000,3.5,89000,...,145651200,10,10,100.0,17894,1,1,2017-01-01,Y,K
9,10,10,0,NEW,20154428,야근 대신 뜨개질,2016-11-17,48000,1.9,48000,...,8286500,7,7,100.0,1239,1,1,2017-01-01,Y,K
10,1,1,2,OLD,20161763,"나, 다니엘 블레이크",2016-12-08,18037800,21.3,-2497400,...,444884100,2085,-352,-14.4,55937,39,65,2017-01-01,Y,F
11,2,2,0,OLD,19890291,해리가 샐리를 만났을 때,1989-11-18,16580900,19.6,-5310400,...,114237200,1885,-656,-25.8,14591,76,103,2017-01-01,Y,F
12,3,3,1,OLD,20160221,에곤 쉴레: 욕망이 그린 그림,2016-12-22,14501600,17.1,-4687000,...,204926700,1687,-548,-24.5,25618,48,66,2017-01-01,Y,F
13,4,4,1,OLD,19930396,시애틀의 잠 못이루는 밤,1993-12-18,10612900,12.5,-4635600,...,67574000,1227,-574,-31.9,8852,61,86,2017-01-01,Y,F
14,5,5,3,OLD,20166401,업 포 러브,2016-12-21,5414100,6.4,-772000,...,85007100,661,-80,-10.8,10792,35,46,2017-01-01,Y,F
15,6,6,3,OLD,19920315,블루 벨벳,1992-10-17,4426500,5.2,-71600,...,23064100,514,-1,-0.2,2615,20,27,2017-01-01,Y,F
16,7,7,3,OLD,20164526,"나의 위대한 친구, 세잔",2016-12-15,3647000,4.3,-284000,...,121098500,486,-23,-4.5,16477,19,23,2017-01-01,Y,F
17,8,8,-1,OLD,20080975,원스 어폰 어 타임 인 아메리카,1984-12-10,895000,1.1,-695000,...,273005500,445,-340,-43.3,23037,1,3,2017-01-01,Y,F
18,9,9,2,OLD,20128588,"그 시절, 우리가 좋아했던 소녀",2012-08-22,2356500,2.8,-1169500,...,329428270,296,-151,-33.8,45442,27,31,2017-01-01,Y,F
19,10,10,3,OLD,20164855,사랑은 부엉부엉,2016-12-29,1698600,2.0,-275000,...,12405200,201,-34,-14.5,1566,21,30,2017-01-01,Y,F
20,1,1,0,OLD,20161725,마스터,2016-12-21,4399793100,83.0,-183705150,...,44184434165,506299,-31485,-5.9,5441619,1245,5721,2017-01-01,N,K
21,2,2,0,OLD,20144641,판도라,2016-12-07,736891900,13.9,-35339100,...,34692290064,87966,-6799,-7.2,4401830,576,1476,2017-01-01,N,K
22,3,3,0,OLD,20152371,"당신, 거기 있어줄래요",2016-12-14,166222000,3.1,-30383700,...,9165307248,18630,-4126,-18.1,1143445,261,572,2017-01-01,N,K
23,4,4,0,OLD,20154661,형,2016-11-23,944000,0.0,-627000,...,23114712293,123,-85,-40.9,2979782,8,9,2017-01-01,N,K
24,5,5,0,NEW,19550028,미망인,1955-12-10,15000,0.0,15000,...,829000,5,5,100.0,362,1,1,2017-01-01,N,K
25,6,6,2,OLD,20163963,어린 아내,2016-11-18,5000,0.0,0,...,846000,1,0,0.0,168,1,1,2017-01-01,N,K
26,7,6,2,OLD,20167689,여비서,2016-12-22,5000,0.0,0,...,48000,1,0,0.0,10,1,1,2017-01-01,N,K
27,1,1,0,OLD,20163183,로그 원: 스타워즈 스토리,2016-12-28,1612424700,39.1,-351990650,...,6739961794,173451,-40093,-18.8,769938,810,3335,2017-01-01,N,F
28,2,2,0,OLD,20162025,씽,2016-12-21,943975500,22.9,-118258900,...,9147833289,115152,-18516,-13.9,1178327,721,1755,2017-01-01,N,F
29,3,3,0,OLD,20167904,라라랜드,2016-12-07,770889600,18.7,-162044100,...,20767028832,87529,-21007,-19.4,2472637,590,1578,2017-01-01,N,F
30,4,4,0,OLD,20161872,너의 이름은.,2017-01-04,325811500,7.9,31854500,...,640998500,37418,3245,9.5,74181,275,342,2017-01-01,N,F
31,5,5,0,OLD,20162727,루돌프와 많이있어,2016-12-28,243890000,5.9,-23742600,...,926773600,29910,-4074,-12.0,119420,372,581,2017-01-01,N,F
32,6,6,0,OLD,20162183,포켓몬 더 무비 XY&Z 「볼케니온 : 기계왕국의 비밀」,2016-12-22,154931400,3.8,-31745800,...,1821568800,19405,-4703,-19.5,238452,300,422,2017-01-01,N,F
33,7,7,0,OLD,20165285,극장판 도라에몽: 신 진구의 버스 오브 재팬,2016-12-21,28628400,0.7,-7085700,...,482548500,3552,-985,-21.7,62699,97,107,2017-01-01,N,F
34,8,8,0,OLD,20165543,하이큐!! 승자와 패자,2016-12-28,14782500,0.4,-8499000,...,160576500,1919,-1174,-38.0,22733,91,142,2017-01-01,N,F
35,9,9,0,OLD,20162365,신비한 동물사전,2016-11-16,11181600,0.3,-966500,...,39311697458,1291,-172,-11.8,4663825,22,27,2017-01-01,N,F
36,10,10,0,NEW,20156062,서부의 사나이,,698000,0.0,698000,...,2894000,349,349,100.0,1468,1,4,2017-01-01,N,F

In [16]:
movie_list = pd.DataFrame({'movieCd': movie.movieCd.drop_duplicates(), 'Rate': 0})

### 영화 상세정보

In [17]:
import json

In [18]:
from json import dumps, loads, JSONEncoder, JSONDecoder
import pickle

class PythonObjectEncoder(JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (list, dict, str, unicode, int, float, bool, type(None))):
            return JSONEncoder.default(self, obj)
        return {'_python_object': pickle.dumps(obj)}

def as_python_object(dct):
    if '_python_object' in dct:
        return pickle.loads(str(dct['_python_object']))
    return dct

In [22]:
class Rectangle:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.area = width * height
 
 
rect = Rectangle(10, 20)
 
# # 사각형 rect 객체를 직렬화 (Serialization)
# with open('', 'wb') as f:
#     pickle.dump(rect, f)
 
 
# # 역직렬화 (Deserialization)
# with open('rect.data', 'rb') as f:
#     r = pickle.load(f)
 
# print("%d x %d" % (r.width, r.height))

In [23]:
def movie_information(lists, keys = key2):
    dict_list = dict()
    url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json'
    
    for movie in lists:
        print(movie)
        payload = {
            'key':keys,
            'movieCd': movie
        }
        
        req = requests.get(url, params = payload)
        
        # 각 영화 코드가 key, 그 결과값으로 나온 json 항목들이 value가 된다
        dict_list[movie] = req.json()['movieInfoResult']['movieInfo']
        
    return dict_list

# 사각형 rect 객체를 직렬화 (Serialization)
with open('movie_information', 'wb') as f:
    pickle.dump(rect, f)
 
 
# 역직렬화 (Deserialization)
with open('movie_information', 'rb') as f:
    r = pickle.load(f)
 
print("%d x %d" % (r.width, r.height))



# movie_detail = movie_information(movie_list)
# prefs = {"movie_information": False}

# with open('movie_information.txt', 'w') as outfile:
#     json.dump(movie_information, outfile)

10 x 20

In [25]:
movie_detail = movie_information(movie_list)

movieCd
Rate

In [27]:
with open('detail.txt', 'wb') as f:
    pickle.dump(rect, f)
    
with open ('detail.txt', 'rb')as f:
    r = pickle.load(f)

In [31]:
with open('movie_information.txt', 'w') as outfile:
    json.dump(movie_information, outfile)

TypeError: Object of type function is not JSON serializable

In [32]:
movie_detail['20161701']

KeyError: '20161701'