In [1]:
from sklearn import svm, metrics
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
import numpy as np

In [2]:
df = pd.read_csv('./data_all/dataset_completed')

In [3]:
del df['Unnamed: 0']

In [4]:
df

,movies,rank,audiCnt,showCnt,NationAtt,RatingAtt,openDt_season,openDt_peak,grade,p_breviews,n_breviews,breviews,p_reviews,n_reviews,reviews,audience_cnt
0,황금 나침반,1,161052,1682,1,3,3,1.0,9.01,245,63,308,34,49,83,2906958
1,내셔널 트레져:비밀의 책,2,123779,1168,1,0,3,1.0,9.06,124,33,157,54,11,65,1745669
2,기다리다 미쳐,3,73572,1553,0,1,3,1.0,8.48,0,0,0,26,24,50,441337
3,색즉시공 시즌2,4,61740,811,0,2,3,1.0,6.58,104,92,196,15,17,32,2002423
4,P.S. 아이 러브 유,6,49842,1061,1,1,3,1.0,9.93,27,1,28,15,6,21,315558
5,어거스트 러쉬,9,47398,476,1,3,2,2.0,9.38,434,70,504,0,0,0,2227459
6,꿀벌대소동,1,52845,1089,1,3,3,1.0,9.02,129,27,156,22,5,27,1238064
7,우리 생애 최고의 순간,1,108071,2042,0,3,3,1.0,9.30,454,67,521,145,31,176,4018872
8,무방비도시,2,81244,1774,0,1,3,1.0,10.00,4,0,4,81,61,142,1600856
9,미스트,3,38391,1100,1,1,3,1.0,8.83,111,30,141,49,78,127,521299
10,마법에 걸린 사랑,5,24385,1425,1,3,3,1.0,9.49,106,12,118,25,10,35,440718
11,스위니 토드 : 어느 잔혹한 이발사 이야기,2,56221,1360,1,2,3,1.0,9.76,304,17,321,65,39,104,698306
12,뜨거운 것이 좋아,4,45365,1507,0,1,3,1.0,8.43,5,2,7,99,59,158,578834
13,클로버필드,2,59123,1917,1,1,3,1.0,9.03,193,43,236,161,160,321,558389
14,더 게임,1,72292,1590,0,1,3,1.0,10.00,4,0,4,112,53,165,1479859
15,슈퍼맨이었던 사나이,3,46803,2050,0,3,3,1.0,8.73,224,55,279,80,43,123,550284
16,명장,5,22361,1203,2,2,3,1.0,8.50,77,27,104,7,8,15,380515
17,6년째 연애중,1,91943,1782,0,1,3,1.0,8.98,142,35,177,47,40,87,1112238
18,마지막 선물,7,18582,1473,0,1,3,1.0,9.41,129,16,145,16,14,30,265362
19,점퍼,10,2082,6,1,1,3,1.0,9.32,152,22,174,51,68,119,1665268
20,추격자,2,113673,2032,0,2,3,1.0,7.50,2,4,6,232,51,283,5046096
21,스파이더위크가의 비밀,5,23559,1120,1,3,3,1.0,9.23,108,15,123,23,14,37,676155
22,데스노트 L: 새로운 시작,3,47833,1339,2,1,3,1.0,8.10,914,317,1231,94,41,135,355158
23,바보,2,66132,1595,0,0,3,1.0,9.47,16,1,17,73,32,105,967654
24,27번의 결혼리허설,4,18026,1157,1,1,0,2.0,8.96,16,7,23,4,6,10,239739
25,마이 뉴 파트너,5,17846,1249,0,1,0,2.0,10.00,1,0,1,4,12,16,260734
26,스텝업 2 : 더 스트리트,7,11196,59,1,0,0,2.0,9.44,105,10,115,28,8,36,1044659
27,"10,000 BC",1,70632,2094,1,1,0,2.0,8.58,59,19,78,19,45,64,1134364
28,천일의 스캔들,5,22105,719,1,1,0,2.0,9.17,21,2,23,10,4,14,693836
29,삼국지:용의 부활,8,3092,15,2,1,0,2.0,8.91,105,32,137,27,28,55,1025302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842,킬러의 보디가드,1,123601,1739,1,1,1,0.0,9.36,141,22,163,181,62,243,1721824
843,발레리안: 천 개 행성의 도시,4,70846,2317,2,0,1,0.0,8.35,216,95,311,232,129,361,511931
844,아토믹 블론드,6,27662,1857,1,2,1,0.0,9.02,122,45,167,70,57,127,155368
845,살인자의 기억법,1,143580,4340,0,1,2,0.0,7.94,703,291,994,812,257,1069,2658589
846,그것,2,76925,3191,1,1,2,0.0,8.86,164,41,205,377,189,566,888836
847,아이 캔 스피크,7,7414,32,0,0,2,0.0,9.33,415,41,456,432,53,485,3282271
848,베이비 드라이버,2,30803,1740,2,1,2,0.0,9.09,87,15,102,86,35,121,823624
849,아메리칸 메이드,3,49188,2899,1,1,2,0.0,8.92,84,17,101,286,60,346,401550
850,범죄도시,9,4025,13,1,2,2,2.0,9.28,1047,162,1209,454,71,525,6880546
851,남한산성,7,3680,19,0,1,2,2.0,8.27,524,187,711,1012,498,1510,3849129
852,킹스맨: 골든 서클,1,481948,7621,1,2,2,0.0,8.98,547,120,667,1267,442,1709,4945486
853,블레이드 러너 2049,8,11660,153,1,1,2,2.0,8.97,771,145,916,270,108,378,322664
854,희생부활자,5,2895,9,0,1,2,2.0,8.88,189,45,234,422,192,614,323628
855,부라더,8,2351,9,0,0,2,2.0,9.11,660,164,824,259,116,375,1492903
856,대장 김창수,9,1803,12,0,0,2,2.0,6.69,286,213,499,373,133,506,381483
857,지오스톰,2,87805,3353,1,0,2,2.0,8.37,90,32,122,418,205,623,1028386
858,토르: 라그나로크,1,415741,7965,1,0,2,2.0,9.40,467,52,519,1293,479,1772,4858572
859,미옥,7,2098,7,0,2,2,2.0,8.36,154,45,199,259,226,485,242737
860,해피 데스데이,3,45059,2230,1,1,2,2.0,9.21,160,23,183,222,67,289,1382650
861,채비,6,13267,1149,0,0,2,2.0,9.47,236,30,266,198,11,209,177439
862,저스티스 리그,1,153553,4132,1,0,2,2.0,8.05,740,339,1079,802,485,1287,1786388
863,7호실,3,55985,2762,0,1,2,2.0,9.03,277,43,320,175,140,315,347823
864,기억의 밤,10,1752,7,0,1,2,2.0,9.25,301,48,349,515,188,703,1387779
865,오리엔트 특급 살인,3,94340,2485,1,0,2,2.0,9.00,206,61,267,342,157,499,864757
866,반드시 잡는다,4,59907,2591,0,1,2,2.0,8.45,207,56,263,180,99,279,446780
867,어쌔신: 더 비기닝,4,31793,2092,1,1,3,1.0,9.22,193,35,228,72,43,115,205544
868,강철비,9,4705,18,0,1,3,1.0,7.48,572,278,850,781,312,1093,4452755
869,스타워즈: 라스트 제다이,2,115246,4313,1,0,3,1.0,8.62,212,64,276,526,261,787,959578
870,신과함께-죄와 벌,7,7906,35,0,0,3,1.0,8.04,2894,1118,4012,1945,653,2598,14411675
871,위대한 쇼맨,3,40995,2736,1,0,3,1.0,9.61,486,41,527,706,55,761,1403026

In [5]:
X = df[ df.columns[1:15] ]
X.head()

,rank,audiCnt,showCnt,NationAtt,RatingAtt,openDt_season,openDt_peak,grade,p_breviews,n_breviews,breviews,p_reviews,n_reviews,reviews
0,1,161052,1682,1,3,3,1.0,9.01,245,63,308,34,49,83
1,2,123779,1168,1,0,3,1.0,9.06,124,33,157,54,11,65
2,3,73572,1553,0,1,3,1.0,8.48,0,0,0,26,24,50
3,4,61740,811,0,2,3,1.0,6.58,104,92,196,15,17,32
4,6,49842,1061,1,1,3,1.0,9.93,27,1,28,15,6,21

In [7]:
def func(x) :
    if 3000000 > int(x) :
        return 1
   
    if 3000000 <= int(x) < 5000000 :
        return 2
     
    if 5000000 <= int(x):
        return 3

In [6]:
Y = df['audience_cnt']

In [8]:
Y = Y.apply(func)

In [9]:
X_train, X_test, Y_train, Y_test= train_test_split( X, Y, test_size=.2 )
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(697, 14) (175, 14) (697,) (175,)

In [10]:
mlp_multilabel = MLPClassifier(hidden_layer_sizes=( 300,100), max_iter=10000, 
                               random_state=42).fit(X_train, Y_train)

0.8228571428571428

In [ ]:
mlp_multilabel.score(X_test, Y_test)

In [11]:
col = X.columns

In [12]:
Y_pred = mlp_multilabel.predict(X_test)
Y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
       1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [13]:
np.sum(Y_test.astype(int) == Y_pred)/Y_test.shape[0]

0.8228571428571428

In [14]:
pre = mlp_multilabel.predict(X_test)

In [15]:
acSore = metrics.accuracy_score(Y_test,pre)
acSore

0.8228571428571428

In [16]:
print(metrics.classification_report(Y_test, pre))

              precision    recall  f1-score   support

           1       0.84      0.97      0.90       143
           2       0.25      0.07      0.11        15
           3       0.67      0.24      0.35        17

   micro avg       0.82      0.82      0.82       175
   macro avg       0.59      0.42      0.45       175
weighted avg       0.77      0.82      0.78       175

In [17]:
np.sum(Y_test.astype(int) == pre)/Y_test.shape[0]

0.8228571428571428

In [18]:
x = np.array(pre)
unique, counts = np.unique(x, return_counts=True)

print(np.asarray((unique, counts)).T)

[[  1 165]
 [  2   4]
 [  3   6]]

In [19]:
Y.value_counts()

1    732
3     73
2     67
Name: audience_cnt, dtype: int64